# $FreeBSD$

COMMENT=	Key-value argument systems
TEXMF_CATEG=	keyval

TEXMF_DIRS_GENERIC+=	expkv expkv-def kvdefinekeys kvsetkeys simplekv \
	xkeyval yax
TEXMF_DIRS_LATEX+=	catoptions clefval keycommand keyreader \
		keyval2e kvoptions ltxkeys options skeycommand \
		skeyval xkeyval 

TEXMF_DOCDIRS+=	generic/simplekv generic/yax
TEXMF_DOCDIRS_LATEX+=	expkv kvdefinekeys kvsetkeys

.include "${.CURDIR}/../texlive-texmf-all/bsd.texmf.mk"
