# $FreeBSD$

COMMENT=	Miscellaneous LaTeX packages 
TEXMF_CATEG=	misc

TEXMF_DIRS_LATEX=	\
	draftcopy draftwatermark easy-todo ed edmargin emptypage engrec \
	enotez epigraph errata etoc everypage exceltex extract fancylabel \
	fancytabs fgruler fixme fixmetodonotes flipbook flowfram fonttable \
	formular fwlw halloweenmath hardwrap hyphenat import ktv-texdata \
	lastpage lcd limap lkproof mailmerge makebase manuscript marginfit \
	marginfix marginnote mathastext maybemath mcaption \
	keystroke \
		romanbar\
		romanbarpagenumber\
		romannum\
		rterface\
		savetrees\
		seealso\
	minidocument\
		refcheck\
		repeatindex\
		multiaudience\
		mnotes\
		minitoc\
		menu\
		menukeys\
		meetingmins\
		needspace\
		nonumonpart\
		nowidow\
		numname\
		numspell\
		paracol\
		pas-tableur\
		phonenumbers\
		progress\
		shadow\
		shadowtext\
		silence\
		standalone\
		subfiles\
		templatetools\
		textfit\
		texvc\
		titling\
		totpages\
		tagging\
		umoline\
		undolabl\
		uri\
		ushort\
		varsfromjobname\
		vwcol\
		wordcount\
		wordlike\
		xellipsis\
		xhfill\
		xwatermark\
		zebra-goodies\
		yagusylo\

TEXMF_DOCDIRS_LATEX=	${TEXMF_DIRS_LATEX}

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
