# $FreeBSD$

COMMENT=	Use CSV files and databases
TEXMF_CATEG=	database

TEXMF_DIRS_LATEX=	csvsimple datatool
TEXMF_DOCDIRS_LATEX=	${TEXMF_DIRS_LATEX}

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
