%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/README
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/bodegraph.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/bodegraph.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/1.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/1.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/10.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/10.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/11.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/11.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/12.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/12.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/13.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/13.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/14.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/14.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/15.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/15.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/16.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/16.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/17.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/17.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/18.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/18.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/19.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/19.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/20.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/20.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/21.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/21.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/22.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/22.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/23.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/23.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/24.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/24.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/25.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/25.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/26.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/26.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/27.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/27.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/28.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/28.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/29.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/29.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/3.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/3.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/30.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/30.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/31.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/31.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/32.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/32.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/33.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/33.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/34.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/34.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/35.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/35.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/36.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/36.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/37.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/37.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/38.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/38.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/39.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/39.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/4.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/4.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/40.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/40.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/41.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/41.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/42.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/42.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/43.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/43.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/44.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/44.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/45.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/45.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/46.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/46.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/47.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/47.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/48.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/48.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/49.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/49.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/5.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/5.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/50.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/50.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/51.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/51.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/52.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/52.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/53.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/53.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/54.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/54.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/55.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/55.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/56.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/56.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/57.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/57.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/58.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/58.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/59.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/59.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/6.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/6.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/60.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/60.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/61.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/61.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/62.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/62.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/63.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/63.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/64.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/64.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/66.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/66.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/67.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/67.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/68.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/68.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/69.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/69.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/7.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/7.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/70.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/70.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/72.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/72.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/73.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/73.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/74.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/74.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/75.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/75.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/76.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/76.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/78.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/78.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/79.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/79.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/8.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/8.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/81.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/81.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/82.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/82.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/83.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/83.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/84.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/84.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/85.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/85.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/86.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/86.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/87.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/87.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/89.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/89.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/9.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/9.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/90.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/90.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/91.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/91.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/93.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/93.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/94.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/94.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/95.gnuplot
%%PORTDOCS%%%%DOCSDIR%%-texmf/bodegraph/gnuplot/bodegraph/95.table
%%PORTDOCS%%%%DOCSDIR%%-texmf/histogr/histogr.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/makeplot/README
%%PORTDOCS%%%%DOCSDIR%%-texmf/makeplot/data1.mat
%%PORTDOCS%%%%DOCSDIR%%-texmf/makeplot/data2.mat
%%PORTDOCS%%%%DOCSDIR%%-texmf/makeplot/makeplot.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/makeplot/mptest.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/mgltex/README
%%PORTDOCS%%%%DOCSDIR%%-texmf/mgltex/Recompilation_decision.eps
%%PORTDOCS%%%%DOCSDIR%%-texmf/mgltex/Recompilation_decision.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/mgltex/Recompilation_decision.svg
%%PORTDOCS%%%%DOCSDIR%%-texmf/mgltex/mgltex.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/mgltex/sample.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/mgltex/sample.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/License.txt
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/NumericPlots.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/README
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/README.TEXLIVE
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/BasicFunctionality.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/FurtherExamples.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/MatlabSupport.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/MultiplePlots.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/NumericPlotsDoc.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/Roll406_Ref2288.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/TechnicalDetails.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/TestPlots.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/BodeDiagramm.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/DataTestRealData.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/DefineData.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/LabelsNTickLabels.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/NyquistPlot.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/Sprungantwort_PT1Glied.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_Boxes.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_EasyPlot.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_Grid.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_Labels.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_Legend.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_LegendI.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_LegendII.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_LegendIII.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_LineStyles.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_Lines.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_LogarithmicI.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_LogarithmicII.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_LogarithmicIII.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_MultipleData.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_Objects.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_PlaceObjects.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_PlaceObjectsII.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_PlotWHoles.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_UseRput.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/basic_UserLinestyles.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/data_BodeDiagrammLinearerTerm.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/data_Nyquist.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/data_SprungantwortPT1Glied.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/furtherEx_TickLabels.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/multiplots_exampleI.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/multiplots_exampleII.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/examples/multiplots_exampleIII.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/fig_NoiseData_ClosedLine.eps
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/fig_NoiseData_OpenLine.eps
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/history.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/keys_NumericDataPlot.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/numericplots/src/options.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfornament/README
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfornament/TeX_box.png
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfornament/baseline.png
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfornament/ornaments.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfornament/ornaments.png
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfornament/ornaments.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfornament/tikzrput.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfornament/tikzrput.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfplots/TeX-programming-notes.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfplots/pgfplots.doc.src.tar.bz2
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfplots/pgfplots.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfplots/pgfplotsexample.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfplots/pgfplotsexample.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfplots/pgfplotstable.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pgfplots/pgfplotstodo.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-2dplot/README
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-2dplot/data1.dat
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-2dplot/data2.dat
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-2dplot/data3.dat
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-2dplot/pst-2dplot-doc.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-2dplot/pst-2dplot-doc.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-3dplot/Changes
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-3dplot/README
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-3dplot/pst-3dplot-doc.bib
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-3dplot/pst-3dplot-doc.dat
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-3dplot/pst-3dplot-doc.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-3dplot/pst-3dplot-doc.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-func/Changes
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-func/README.md
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-func/pst-func-doc.bib
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-func/pst-func-doc.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-func/pst-func-doc.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-func/pst-func-doc.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-infixplot/README
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-infixplot/pst-infixplot-doc.ps
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-infixplot/pst-infixplot-doc.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-infixplot/pst-infixplot.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/Changes
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/README
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/Data.dat
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/LSM.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/LSM2.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/boxplot.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/data.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/data1.dat
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/data3.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/dataMul.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/demo.txt
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/demo0.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/demo1.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/demo2.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/demo3.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/dotmatrix.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/pst-plot-doc.eps
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/pstricks-add-data9.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/data/test.data
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/pst-plot-doc.bib
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/pst-plot-doc.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/pst-plot/pst-plot-doc.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tikz-3dplot/CHANGELOG
%%PORTDOCS%%%%DOCSDIR%%-texmf/tikz-3dplot/README
%%PORTDOCS%%%%DOCSDIR%%-texmf/tikz-3dplot/externalize_images.bat
%%PORTDOCS%%%%DOCSDIR%%-texmf/tikz-3dplot/tikz-3dplot_documentation.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/tikz-3dplot/tikz-3dplot_documentation.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tikz-3dplot/tikz-3dplot_documentation_figures.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/README
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/Makefile
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/info_fct_tex.txt
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-1-0-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-10-2-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-10-3-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-10-4-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-10-5-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-10-6-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-10-7-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-10-8-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-11-1-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-11-2-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-11-3-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-11-4-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-11-5-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-11-6-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-11-7-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-12-1-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-12-2-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-12-3-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-12-4-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-12-5-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-12-6-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-13-0-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-1-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-2-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-3-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-4-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-5-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-6-1.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-7-1.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-7-2.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-7-3.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-7-4.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-8-1.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-14-8-2.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-15-0-3.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-15-0-4.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-16-1-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-16-2-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-3-3-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-3-4-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-4-2-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-4-3-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-4-4-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-4-5-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-4-6-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-4-7-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-4-8-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-5-1-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-5-2-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-5-3-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-5-4-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-5-5-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-5-6-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-6-1-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-7-10-2.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-7-2-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-7-3-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-7-4-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-7-5-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-7-6-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-7-7-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-7-8-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-7-9-1.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-8-10-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-8-11-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-8-2-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-8-3-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-8-4-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-8-6-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-8-7-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-8-8-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-8-9-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-9-1-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-9-2-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-9-3-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/latex/tkzFct-9-4-0.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/examples/tkzfctpreamble.ltx
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-VDW.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-area.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-asymptote.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-bac.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-compilation.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-example.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-faq.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-fonctions.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-fppgf.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-installation.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-interpolation.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-label.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-liste.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-main.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-param.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-point.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-polar.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-riemann.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-symbol.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-tangent.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/TKZdoc-fct-why.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/latex/fct.ist
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/readme-tkz-fct-fr.txt
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/readme-tkz-fct.txt
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/readme.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-fct/tkz-fct-screen.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-kiviat/TKZdoc-kiviat-main.pdf
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-kiviat/examples/latex/file.dat
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-kiviat/examples/latex/kiviat1.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-kiviat/examples/latex/kiviat2.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-kiviat/examples/latex/kiviat3.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-kiviat/examples/latex/kiviat4.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-kiviat/examples/latex/kiviat5.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-kiviat/latex/TKZdoc-kiviat-main.tex
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-kiviat/latex/file.dat
%%PORTDOCS%%%%DOCSDIR%%-texmf/tkz-kiviat/latex/file2.dat
%%TEXMFDIR%%scripts/pgfplots/matlab2pgfplots.m
%%TEXMFDIR%%scripts/pgfplots/matlab2pgfplots.sh
%%TEXMFDIR%%scripts/pgfplots/pgf2pdf.sh
%%TEXMFDIR%%scripts/pgfplots/pgfplots.py
%%TEXMFDIR%%tex/generic/pst-plot/pst-plot.tex
%%TEXMFDIR%%tex/generic/pst-plot/pst-plot97.tex
%%TEXMFDIR%%tex/latex/bodegraph/bodegraph.sty
%%TEXMFDIR%%tex/latex/histogr/histogr.sty
%%TEXMFDIR%%tex/latex/makeplot/makeplot.sty
%%TEXMFDIR%%tex/latex/mgltex/mgltex.sty
%%TEXMFDIR%%tex/latex/numericplots/NumericPlots.sty
%%TEXMFDIR%%tex/latex/numericplots/NumericPlots_TickLabels.tex
%%TEXMFDIR%%tex/latex/numericplots/NumericPlots_labels.tex
%%TEXMFDIR%%tex/latex/numericplots/NumericPlots_legend.tex
%%TEXMFDIR%%tex/latex/numericplots/NumericPlots_macros.tex
%%TEXMFDIR%%tex/latex/numericplots/NumericPlots_styles.tex
%%TEXMFDIR%%tex/latex/pgfornament/pgflibraryam.code.tex
%%TEXMFDIR%%tex/latex/pgfornament/pgflibraryvectorian.code.tex
%%TEXMFDIR%%tex/latex/pgfornament/pgfornament.sty
%%TEXMFDIR%%tex/latex/pgfornament/tikzrput.sty
%%TEXMFDIR%%tex/latex/pgfplots/bugtracker.sty
%%TEXMFDIR%%tex/latex/pgfplots/libs/tikzlibrarypgfplots.clickable.code.tex
%%TEXMFDIR%%tex/latex/pgfplots/libs/tikzlibrarypgfplotsclickable.code.tex
%%TEXMFDIR%%tex/latex/pgfplots/pgfplots.sty
%%TEXMFDIR%%tex/latex/pgfplots/pgfplotstable.sty
%%TEXMFDIR%%tex/latex/pgfplots/pgfregressiontest.sty
%%TEXMFDIR%%tex/latex/pst-2dplot/pst-2dplot.sty
%%TEXMFDIR%%tex/latex/pst-3dplot/pst-3dplot.sty
%%TEXMFDIR%%tex/latex/pst-func/pst-func.sty
%%TEXMFDIR%%tex/latex/pst-infixplot/infix-RPN.sty
%%TEXMFDIR%%tex/latex/pst-infixplot/pst-infixplot.sty
%%TEXMFDIR%%tex/latex/pst-plot/pst-plot.sty
%%TEXMFDIR%%tex/latex/tikz-3dplot/tikz-3dplot.sty
%%TEXMFDIR%%tex/latex/tkz-fct/tkz-fct.sty
%%TEXMFDIR%%tex/latex/tkz-kiviat/tkz-kiviat.sty
