# $FreeBSD$

COMMENT=	Large collection of add-on packages for LaTeX
TEXMF_CATEG=	latexextra

TEXMF_DIRS=	bibtex/bib/attachfile/ \
		bibtex/bib/directory/ \
		bibtex/bib/frankenstein/ \
		bibtex/bib/gloss/ \
		bibtex/bib/glossaries-extra/ \
		bibtex/bib/lsc/ \
		bibtex/bib/msc/ \
		bibtex/bst/achemso/ \
		bibtex/bst/adrconv/ \
		bibtex/bst/chet/ \
		bibtex/bst/datatool/ \
		bibtex/bst/directory/ \
		bibtex/bst/dlfltxb/ \
		bibtex/bst/dvdcoll/ \
		bibtex/bst/frankenstein/ \
		bibtex/bst/gloss/ \
		bibtex/bst/hc/ \
		bibtex/bst/mciteplus/ \
		bibtex/bst/mslapa/ \
		bibtex/bst/opcit/ \
		bibtex/bst/phfnote/ \
		bibtex/bst/savetrees/ \
		bibtex/bst/shipunov/ \
		bibtex/bst/upmethodology/ \
		dvips/esint-type1/ \
		fonts/source/public/casyl/ \
		fonts/source/public/cbcoptic/ \
		fonts/source/public/circ/ \
		fonts/source/public/clock/ \
		fonts/source/public/esint/ \
		fonts/source/public/niceframe/ \
		fonts/source/public/trsym/ \
		fonts/tfm/public/casyl/ \
		fonts/tfm/public/cbcoptic/ \
		fonts/tfm/public/circ/ \
		fonts/tfm/public/clock/ \
		fonts/tfm/public/epiolmec/ \
		fonts/tfm/public/esint/ \
		fonts/tfm/public/niceframe/ \
		fonts/tfm/public/relenc/ \
		fonts/tfm/public/scanpages/ \
		fonts/tfm/public/trsym/ \
		fonts/type1/public/cbcoptic/ \
		fonts/type1/public/epiolmec/ \
		fonts/type1/public/esint-type1/ \
		fonts/type1/public/scanpages/ \
		fonts/vf/public/relenc/ \
		makeindex/gmdoc/ \
		makeindex/iso/ \
		makeindex/leipzig/ \
		makeindex/nomencl/ \
		makeindex/nomentbl/ \
		makeindex/repeatindex/ \
		makeindex/xdoc/ \
		metapost/makecirc/ \
		scripts/changes/ \
		scripts/flowfram/ \
		scripts/fmtcount/ \
		scripts/l3build/ \
		scripts/markdown/ \
		scripts/mfirstuc/ \
		scripts/mycv/ \
		scripts/pax/ \
		scripts/shipunov/ \
		scripts/splitindex/ \
		tex/context/third/markdown/ \
		tex/generic/2up/ \
		tex/generic/filemod/ \
		tex/generic/formlett/ \
		tex/generic/markdown/ \
		tex/generic/minifp/ \
		tex/generic/poster-mac/ \
		tex/generic/rlepsf/ \
		tex/generic/shapepar/ \
		tex/generic/splitindex/ \
		tex/generic/textmerg/ \
		tex/generic/xcomment/ \
		tex/generic/xint/ \
		tex/generic/xstring/ \
		tex/generic/ydoc/\
		tex/luatex/markdown/ \
		tex/plain/esint-type1/ \
		tex/plain/standalone/

TEXMF_DIRS_LATEX=	\
		ESIEEcv GS1  Tabbing a0poster \
		abraces abstract achemso \
		acro acronym acroterm actuarialangle \
		actuarialsymbol addfont adjmulticol \
		adjustbox adrconv advdate akktex akletter \
		alnumsec altfont \
		amsaddr animate anonchap anyfontsize \
		appendix apptools arcs \
		arydshln asciilist assignment \
		attachfile aurl \
		authorarchive authorindex autonum autopdf \
		avremu background bankstatement bashful \
		basicarith bchart \
		beton bez123 bezos bibletext \
		bigfoot bigints biochemistry-colors bizcard \
		block blowup bnumexpr bold-extra \
		bookcover bookest booklet bophook \
		boxhandler bracketkey breakurl \
		bullcntr bussproofs bxcalc bxdpx-beamer bxdvidriver \
		bxenclose bxnewfont bxpapersize bxpdfver bxtexlogo \
		calcage calctab calculator calrsfs calxxxx-yyyy \
		capt-of captcont captdef carbohydrates \
		cases casyl catechis \
		cbcoptic ccaption cclicenses cd-cover cd cdpbundl \
		censor changebar changelayout changepage \
		changes chappg chapterfolder cheatsheet chet chextras \
		childdoc chkfloat chletter chronology circ \
		classics classpack clefval cleveref clipboard clock \
		cmdtrack cmsd \
		codedoc codepage codesection \
		colordoc colorinfo coloring colorspace colorwav \
		colorweb combelow combine comma \
		comment concepts concprog constants continue \
		contour contracard cooking-units cooking \
		cool coollist coolstr coolthms cooltooltips \
		coordsys copyedit copyrightbox coseoul counttexruns \
		coursepaper coverpage cprotect \
		crossreference crossreftools csquotes css-colors \
		cuisine currency currfile \
		cutwin cweb-latex cyber cybercic \
		dashrule dashundergaps dataref dateiliste \
		datenumber datetime datetime2-bahasai datetime2-basque \
		datetime2-breton datetime2-bulgarian datetime2-catalan \
		datetime2-croatian datetime2-czech datetime2-danish \
		datetime2-dutch datetime2-en-fulltext datetime2-english \
		datetime2-esperanto datetime2-estonian datetime2-finnish \
		datetime2-french datetime2-galician datetime2-german \
		datetime2-greek datetime2-hebrew datetime2-icelandic \
		datetime2-irish datetime2-it-fulltext datetime2-italian \
		datetime2-latin datetime2-lsorbian datetime2-magyar \
		datetime2-norsk datetime2-polish datetime2-portuges \
		datetime2-romanian datetime2-russian datetime2-samin \
		datetime2-scottish datetime2-serbian datetime2-slovak \
		datetime2-slovene datetime2-spanish datetime2-swedish \
		datetime2-turkish datetime2-ukrainian datetime2-usorbian \
		datetime2-welsh datetime2 dblfloatfix decimal decorule \
		delimtxt denisbdoc diagnose dichokey \
		dinbrief directory dirtytalk dlfltxb dnaseq doclicense \
		docmfp docmute doctools documentation doi dotarrow dotseqn \
		download dox dpfloat dprogress draftcopy draftfigure \
		draftwatermark dtk dtxdescribe ducksay dvdcoll \
		dynamicnumber ean13isbn easy-todo easy \
		easyfig easyformat easylist easyreview ebezier ecclesiastic \
		ed edmargin eemeir egplot elements ellipsis elmath \
		elzcards emarks embedall embrac emptypage \
		emulateapj endfloat endheads endnotes engpron engrec enotez \
		enumitem-zref envbig envlab epigraph \
		epiolmec eqell eqlist eqnalign eqname errata \
		esdiff esint etaremune etextools etoc eukdate \
		eulerpx everypage \
		example examplep exceltex excludeonly \
		expdlist\
		extract\
		facsimile\
		factura\
		fancylabel\
		fancynum\
		fancypar\
		fancytabs\
		fancytooltips\
		fgruler\
		figsize\
		filecontentsdef\
		filedate\
		fileinfo\
		filemod\
		fink\
		fithesis\
		fixcmex\
		fixfoot\
		fixme\
		fixmetodonotes\
		flabels\
		flacards\
		flagderiv\
		flashcards\
		flashmovie\
		flipbook\
		flippdf\
		floatflt\
		floatrow\
		flowfram\
		fmp\
		fmtcount\
		fn2end\
		fnbreak\
		fncychap\
		fncylab\
		fnpara\
		fnpct\
		fnumprint\
		fontaxes\
		fonttable\
		footmisc\
		footmisx\
		footnotebackref\
		footnoterange\
		footnpag\
		foreign\
		forms16be\
		formular\
		fragments\
		frankenstein\
		frege\
		ftnxtra\
		fullblck\
		fullminipage\
		fundus-calligra\
		fundus-cyr\
		fundus-sueterlin\
		fvextra\
		fwlw\
		g-brief\
		gauss\
		gcard\
		gcite\
		gender\
		getfiledate\
		ginpenc\
		gloss\
		glossaries-danish\
		glossaries-dutch\
		glossaries-english\
		glossaries-extra\
		glossaries-finnish\
		glossaries-french\
		glossaries-german\
		glossaries-irish\
		glossaries-italian\
		glossaries-magyar\
		glossaries-polish\
		glossaries-portuges\
		glossaries-serbian\
		glossaries-spanish\
		glossaries\
		gmdoc-enhance\
		gmdoc\
		gmiflink\
		gmverb\
		graphbox\
		graphicx-psmin\
		grayhints\
		grfpaste\
		grid-system\
		grid\
		gridset\
		guitlogo\
		halloweenmath\
		handin\
		hang\
		hanging\
		hardwrap\
		harpoon\
		hc\
		he-she\
		hhtensor\
		hitec\
		hletter\
		hpsdiss\
		hrefhide\
		hvindex\
		hypdvips\
		hyper\
		hypernat\
		hyperxmp\
		hyphenat\
		idxcmds\
		idxlayout\
		iffont\
		ifplatform\
		iitem\
		image-gallery\
		imakeidx\
		import\
		incgraph\
		indextools\
		inlinedef\
		inputtrc\
		interactiveworkbook\
		interfaces\
		intopdf\
		invoice\
		invoice2\
		iso\
		iso10303\
		isodate\
		isodoc\
		isonums\
		isopt\
		isorot\
		isotope\
		issuulinks\
		iwhdp\
		jlabels\
		jumplines\
		jvlisting\
		kerntest\
		keycommand\
		keyfloat\
		keyreader\
		keystroke\
		keyval2e\
		kix\
		knowledge\
		koma-script-sfs\
		ktv-texdata\
		l3build\
		labbook\
		labels\
		labelschanged\
		lastpackage\
		lastpage\
		latexdemo\
		lazylist\
		lccaps\
		lcd\
		lcg\
		leading\
		leaflet\
		leftidx\
		leipzig\
		lengthconvert\
		lettre\
		lettrine\
		lewis\
		libgreek\
		limap\
		linegoal\
		linop\
		lisp-on-tex\
		listing\
		listlbls\
		listofsymbols\
		lkproof\
		logical-markup-utils\
		logpap\
		longnamefilelist\
		lsc\
		lstaddons\
		ltabptch\
		ltxdockit\
		ltxindex\
		ltxkeys\
		ltxnew\
		ltxtools\
		magaz\
		mailing\
		mailmerge\
		makebarcode\
		makebase\
		makedtx\
		makeglos\
		mandi\
		manfnt\
		manuscript\
		marginfit\
		marginfix\
		marginnote\
		markdown\
		mathalfa\
		mathastext\
		mathfam256\
		maybemath\
		mbenotes\
		mcaption\
		mceinleger\
		mcite\
		mciteplus\
		media9\
		meetingmins\
		memexsupp\
		mensa-tex\
		menu\
		menukeys\
		method\
		metre\
		mftinc\
		midpage\
		minidocument\
		minitoc\
		minorrevision\
		minted\
		minutes\
		mla-paper\
		mlist\
		mmap\
		mnotes\
		modernposter\
		modref\
		modroman\
		modular\
		monofill\
		moreenum\
		morefloats\
		morehype\
		moresize\
		moreverb\
		morewrites\
		movie15\
		mparhack\
		mpostinl\
		msc\
		msg\
		mslapa\
		mtgreek\
		multenum\
		multiaudience\
		multibbl\
		multicap\
		multilang\
		mversion\
		mwe\
		mylatexformat\
		nag\
		nameauth\
		namespc\
		ncclatex\
		ncctools\
		needspace\
		nestquot\
		newfile\
		newlfm\
		newspaper\
		newunicodechar\
		newvbtm\
		newverbs\
		nfssext-cfr\
		nicefilelist\
		niceframe\
		nicetext\
		nidanfloat\
		nlctdoc\
		noitcrul\
		nolbreaks\
		nomencl\
		nomentbl\
		nonfloat\
		nonumonpart\
		nopageno\
		normalcolor\
		notes\
		notespages\
		notestex\
		notoccite\
		nowidow\
		ntheorem\
		numberedblock\
		numname\
		numspell\
		ocg-p\
		ocgx\
		ocgx2\
		ocr-latex\
		octavo\
		oldstyle\
		onlyamsmath\
		opcit\
		optidef\
		optional\
		options\
		outline\
		outliner\
		outlines\
		outlining\
		overpic\
		pagecolor\
		pagecont\
		pagenote\
		pageslts\
		paper\
		papercdcase\
		papermas\
		papertex\
		paracol\
		parades\
		paralist\
		paresse\
		parnotes\
		pas-tableur\
		pauldoc\
		pawpict\
		pax\
		pdf14\
		pdfcomment\
		pdfcprot\
		pdfmarginpar\
		pdfpagediff\
		pdfprivacy\
		pdfreview\
		pdfsync\
		pdfwin\
		pdfx\
		pecha\
		perltex\
		permute\
		petiteannonce\
		phffullpagefigure\
		phfnote\
		phfparen\
		phfqit\
		phfquotetext\
		phfthm\
		philex\
		phonenumbers\
		photo\
		piff\
		pkgloader\
		placeins\
		plantslabels\
		plates\
		plweb\
		polynom\
		polynomial\
		postcards\
		preprint\
		pressrelease\
		prettyref\
		preview\
		printlen\
		program\
		progress\
		progressbar\
		proofread\
		protex\
		protocol\
		psfragx\
		pstool\
		pstring\
		pxgreeks\
		pygmentex\
		python\
		qstest\
		qsymbols\
		quicktype\
		quotchap\
		quoting\
		quotmark\
		randtext\
		readarray\
		recipe\
		recipebook\
		recipecard\
		refcheck\
		refenums\
		reflectgraphics\
		refman\
		refstyle\
		regcount\
		register\
		regstats\
		relenc\
		repeatindex\
		repltext\
		rjlparshap\
		robustindex\
		romanbar\
		romanbarpagenumber\
		romanneg\
		romannum\
		rotfloat\
		rotpages\
		rterface\
		rtkinenc\
		rulercompass\
		sanitize-umlaut\
		sauerj\
		savefnmark\
		savetrees\
		scalebar\
		scalerel\
		scanpages\
		scrlttr2copy\
		sdrt\
		secdot\
		sectionbox\
		sectionbreak\
		sectsty\
		seealso\
		selectp\
		semantic-markup\
		semantic\
		semioneside\
		semproc\
		sepfootnotes\
		seqsplit\
		sf298\
		sffms\
		sfmath\
		shadethm\
		shadow\
		shadowtext\
		shdoc\
		shipunov\
		shorttoc\
		show2e\
		showcharinbox\
		showdim\
		showexpl\
		sidecap\
		sidenotes\
		silence\
		simplecd\
		simpleinvoice\
		sitem\
		skb\
		skdoc\
		skeyval\
		skrapport\
		slantsc\
		smalltableof\
		smartref\
		smartunits\
		snapshot\
		snotez\
		soul\
		spark-otf\
		sparklines\
		splitindex\
		spotcolor\
		spverbatim\
		srbook-mem\
		srcltx\
		sseq\
		standalone\
		statistik\
		stealcaps\
		stex\
		stringstrings\
		sttools\
		stubs\
		subdepth\
		subeqn\
		subeqnarray\
		subfigmat\
		subfigure\
		subfiles\
		subfloat\
		substitutefont\
		svg\
		svgcolor\
		syntax\
		syntrace\
		synttree\
		tabfigures\
		tableaux\
		tableof\
		tablists\
		tabto-ltx\
		tagging\
		tagpair\
		tamefloats\
		tcldoc\
		tdclock\
		technics\
		ted\
		templatetools\
		termcal\
		termlist\
		testhyphens\
		testidx\
		tex-label\
		texlogos\
		texmate\
		texments\
		texshade\
		textfit\
		textpos\
		textualicomma\
		texvc\
		theoremref\
		thinsp\
		thmtools\
		threadcol\
		thumb\
		thumbs\
		thumby\
		ticket\
		titlecaps\
		titlefoot\
		titlepic\
		titleref\
		titling\
		tocbibind\
		tocdata\
		tocloft\
		tocvsec2\
		todo\
		todonotes\
		tokenizer\
		topfloat\
		totpages\
		trfsigns\
		trivfloat\
		trsym\
		truncate\
		turnthepage\
		twoinone\
		twoup\
		txgreeks\
		type1cm\
		typed-checklist\
		typeface\
		typoaid\
		typogrid\
		uassign\
		umoline\
		underlin\
		underoverlap\
		undolabl\
		units\
		upmethodology\
		upquote\
		uri\
		ushort\
		uspace\
		variablelm\
		varindex\
		varsfromjobname\
		vdmlisting\
		verbasef\
		verbatimcopy\
		verbdef\
		verbments\
		version\
		versions\
		versonotes\
		vertbars\
		vgrid\
		volumes\
		vpe\
		vruler\
		vwcol\
		wallpaper\
		warning\
		was\
		widetable\
		wordcount\
		wordlike\
		wrapfig\
		wtref\
		xcolor-material\
		xcolor-solarized\
		xdoc\
		xellipsis\
		xhfill\
		xmpincl\
		xnewcommand\
		xoptarg\
		xprintlen\
		xurl\
		xwatermark\
		xytree\
		yafoot\
		yagusylo\
		yaletter\
		ycbook\
		ydoc\
		yplan\
		zebra-goodies\
		zed-csp\
		ziffer\
		zwgetfdate
TEXMF_DOCDIRS=
TEXMF_DOCDIRS_LATEX=	${TEXMF_DIRS_LATEX:Nbeamerthemejltree:Nclasspack:Neqname:Neulerpx:Nexample:Nfundus-cyr:Nmakedtx:Nmanfnt:Nnestquot:Nnextpage:Nsavesym:Nsfmath:Nspark-otf:Nstack:Ntexlogos:Ntitlefoot:Nvariablelm}

USES=	perl5 python

TEXMF_SHEBANG_FILES=	\
	share/texmf-dist/scripts/changes/delcmdchanges.bash \
	share/texmf-dist/scripts/shipunov/biokey2html.sh \
	share/texmf-dist/scripts/mycv/mycv_split_contents.pl
TEXMF_SHEBANG_FILES_DOCS=	\
	share/doc/texlive-texmf/uspace/uspace-ctanify.sh\
	share/doc/texlive-texmf/pdfreview/pdfreview.sh\
	share/doc/texlive-texmf/pdfreview/pdfshrink.sh\
	share/doc/texlive-texmf/shdoc/shreformat.sh\
	share/doc/texlive-texmf/scanpages/replicate.py

post-install-texmf:
	# Part of texlive-bin
.for script in l3build/l3build.lua pax/pdfannotextractor.pl splitindex/splitindex.pl
	${RM} ${STAGEDIR}${LOCALBASE}/share/texmf-dist/scripts/${script}
.endfor

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
