# $FreeBSD$

COMMENT=	Large collection of add-on packages for LaTeX
TEXMF_CATEG=	latexextra

TEXMF_DIRS=	bibtex/bib/attachfile/ \
		bibtex/bib/directory/ \
		bibtex/bib/frankenstein/ \
		bibtex/bib/gloss/ \
		bibtex/bib/glossaries-extra/ \
		bibtex/bib/lsc/ \
		bibtex/bib/msc/ \
		bibtex/bst/achemso/ \
		bibtex/bst/adrconv/ \
		bibtex/bst/chet/ \
		bibtex/bst/datatool/ \
		bibtex/bst/directory/ \
		bibtex/bst/dlfltxb/ \
		bibtex/bst/dvdcoll/ \
		bibtex/bst/frankenstein/ \
		bibtex/bst/gloss/ \
		bibtex/bst/hc/ \
		bibtex/bst/mciteplus/ \
		bibtex/bst/mslapa/ \
		bibtex/bst/opcit/ \
		bibtex/bst/phfnote/ \
		bibtex/bst/savetrees/ \
		bibtex/bst/shipunov/ \
		bibtex/bst/upmethodology/ \
		dvips/esint-type1/ \
		fonts/source/public/casyl/ \
		fonts/source/public/cbcoptic/ \
		fonts/source/public/circ/ \
		fonts/source/public/clock/ \
		fonts/source/public/esint/ \
		fonts/source/public/niceframe/ \
		fonts/afm/public/niceframe-type1/ \
		fonts/source/public/trsym/ \
		fonts/tfm/public/casyl/ \
		fonts/tfm/public/cbcoptic/ \
		fonts/tfm/public/circ/ \
		fonts/tfm/public/clock/ \
		fonts/source/public/dingbat/ \
		fonts/tfm/public/dingbat/ \
		fonts/tfm/public/epiolmec/ \
		fonts/tfm/public/esint/ \
		fonts/tfm/public/niceframe/ \
		fonts/type1/public/niceframe-type1/ \
		fonts/tfm/public/relenc/ \
		fonts/tfm/public/scanpages/ \
		fonts/tfm/public/trsym/ \
		fonts/type1/public/cbcoptic/ \
		fonts/type1/public/epiolmec/ \
		fonts/type1/public/esint-type1/ \
		fonts/type1/public/scanpages/ \
		fonts/vf/public/relenc/ \
		makeindex/gmdoc/ \
		makeindex/iso/ \
		makeindex/leipzig/ \
		makeindex/nomencl/ \
		makeindex/nomentbl/ \
		makeindex/repeatindex/ \
		makeindex/xdoc/ \
		metapost/makecirc/ \
		scripts/changes/ \
		scripts/flowfram/ \
		scripts/fmtcount/ \
		scripts/l3build/ \
		scripts/markdown/ \
		scripts/mfirstuc/ \
		scripts/mycv/ \
		scripts/pax/ \
		scripts/shipunov/ \
		scripts/splitindex/ \
		tex/context/third/markdown/ \
		tex/luatex/markdown/ \
		tex/plain/esint-type1/ \
		tex/plain/standalone/

TEXMF_DIRS_GENERIC=	\
	2up filemod formlett markdown minifp poster-mac \
	rlepsf shapepar splitindex textmerg \
	xcomment xint xstring ydoc
TEXMF_DIRS_LATEX=	\
		ESIEEcv GS1 Tabbing \
		acro acronym acroterm \
		addfont \
		advdate akktex akletter \
		altfont \
		amsaddr anonchap anyfontsize \
		appendix apptools arcs \
		aurl \
		authorindex autonum \
		avremu bankstatement \
		beton bezos bibletext \
		bigfoot \
		block bold-extra \
		bookest \
		bracketkey breakurl \
		bxcalc bxdvidriver \
		bxnewfont bxtexlogo \
		calrsfs calxxxx-yyyy \
		captcont captdef \
		cases casyl catechis \
		ccaption cclicenses cd-cover cd cdpbundl \
		censor changebar \
		changes chappg chapterfolder chet chextras \
		childdoc chkfloat chletter \
		classics cleveref \
		cmsd \
		codepage \
		colorinfo \
		colorweb combelow combine \
		concprog constants continue \
		contracard cooking-units cooking \
		coolthms \
		coseoul counttexruns \
		coursepaper \
		crossreference crossreftools csquotes \
		cuisine \
		cutwin cweb-latex cyber cybercic \
		dashrule dashundergaps dateiliste \
		datenumber datetime datetime2-bahasai datetime2-basque \
		datetime2-breton datetime2-bulgarian datetime2-catalan \
		datetime2-croatian datetime2-czech datetime2-danish \
		datetime2-dutch datetime2-en-fulltext datetime2-english \
		datetime2-esperanto datetime2-estonian datetime2-finnish \
		datetime2-french datetime2-galician datetime2-german \
		datetime2-greek datetime2-hebrew datetime2-icelandic \
		datetime2-irish datetime2-it-fulltext datetime2-italian \
		datetime2-latin datetime2-lsorbian datetime2-magyar \
		datetime2-norsk datetime2-polish datetime2-portuges \
		datetime2-romanian datetime2-russian datetime2-samin \
		datetime2-scottish datetime2-serbian datetime2-slovak \
		datetime2-slovene datetime2-spanish datetime2-swedish \
		datetime2-turkish datetime2-ukrainian datetime2-usorbian \
		datetime2-welsh datetime2 dblfloatfix \
		delimtxt dichokey \
		dingbat dinbrief directory dirtytalk dlfltxb dnaseq doclicense \
		docmfp documentation doi dotarrow \
		dox dpfloat draftfigure \
		dynamicnumber easy \
		easyfig easyformat easylist easyreview ebezier ecclesiastic \
		eemeir egplot ellipsis elmath \
		emarks embrac \
		endfloat endheads endnotes \
		envbig envlab \
		epiolmec eqell eqnalign eqname \
		etextools eukdate \
		eulerpx \
		examplep excludeonly \
		fancynum\
		figsize\
		filecontentsdef\
		fixcmex\
		fixfoot\
		flabels\
		floatflt\
		floatrow\
		fmp\
		fn2end\
		fnbreak\
		fncychap\
		fncylab\
		fnpara\
		fnpct\
		fnumprint\
		fontaxes\
		footmisc\
		footmisx\
		footnotebackref\
		footnoterange\
		footnpag\
		forms16be\
		fragments\
		frankenstein\
		frege\
		ftnxtra\
		fullblck\
		fullminipage\
		fundus-cyr\
		fundus-sueterlin\
		fvextra\
		gcite\
		gender\
		ginpenc\
		gloss\
		glossaries-danish\
		glossaries-dutch\
		glossaries-english\
		glossaries-extra\
		glossaries-finnish\
		glossaries-french\
		glossaries-german\
		glossaries-irish\
		glossaries-italian\
		glossaries-magyar\
		glossaries-polish\
		glossaries-portuges\
		glossaries-serbian\
		glossaries-spanish\
		glossaries\
		gmiflink\
		gmverb\
		graphbox\
		graphicx-psmin\
		grfpaste\
		gridset\
		guitlogo\
		hang\
		hanging\
		harpoon\
		hc\
		he-she\
		hitec\
		hletter\
		hrefhide\
		hvindex\
		hypdvips\
		hyper\
		hypernat\
		hyperxmp\
		idxcmds\
		idxlayout\
		iffont\
		imakeidx\
		indextools\
		interfaces\
		iso\
		iso10303\
		isodate\
		isonums\
		isopt\
		isorot\
		issuulinks\
		jlabels\
		jumplines\
		jvlisting\
		kerntest\
		keyfloat\
		keyreader\
		kix\
		knowledge\
		koma-script-sfs\
		l3build\
		labels\
		labelschanged\
		latexdemo\
		lazylist\
		lccaps\
		leading\
		lengthconvert\
		lettrine\
		libgreek\
		linegoal\
		lisp-on-tex\
		listing\
		listlbls\
		listofsymbols\
		logical-markup-utils\
		longnamefilelist\
		lsc\
		lstaddons\
		ltxdockit\
		ltxindex\
		mailing\
		makedtx\
		makeglos\
		manfnt\
		mathalfa\
		mathfam256\
		mcite\
		mciteplus\
		memexsupp\
		method\
		mftinc\
		minorrevision\
		minutes\
		modref\
		modular\
		monofill\
		morefloats\
		morehype\
		moresize\
		moreverb\
		morewrites\
		mparhack\
		mpostinl\
		msg\
		mtgreek\
		multibbl\
		multicap\
		multilang\
		mversion\
		mwe\
		mylatexformat\
		nag\
		nameauth\
		namespc\
		ncclatex\
		ncctools\
		needspace\
		nestquot\
		newfile\
		newlfm\
		newspaper\
		newunicodechar\
		newvbtm\
		newverbs\
		nfssext-cfr\
		nicefilelist\
		niceframe\
		nicetext\
		nidanfloat\
		nlctdoc\
		noitcrul\
		nolbreaks\
		nomencl\
		nomentbl\
		nonfloat\
		nonumonpart\
		nopageno\
		normalcolor\
		notes\
		notespages\
		notestex\
		notoccite\
		nowidow\
		ntheorem\
		numberedblock\
		numname\
		numspell\
		ocg-p\
		ocgx\
		ocgx2\
		ocr-latex\
		octavo\
		oldstyle\
		onlyamsmath\
		opcit\
		optidef\
		optional\
		options\
		outline\
		outliner\
		outlines\
		outlining\
		overpic\
		pagecolor\
		pagecont\
		pagenote\
		pageslts\
		paper\
		papercdcase\
		papermas\
		papertex\
		paracol\
		parades\
		paralist\
		paresse\
		parnotes\
		pas-tableur\
		pauldoc\
		pawpict\
		pax\
		pecha\
		perltex\
		permute\
		petiteannonce\
		phffullpagefigure\
		phfnote\
		phfparen\
		phfqit\
		phfquotetext\
		phfthm\
		philex\
		phonenumbers\
		photo\
		piff\
		pkgloader\
		placeins\
		plantslabels\
		plates\
		plweb\
		polynom\
		polynomial\
		postcards\
		preprint\
		pressrelease\
		prettyref\
		preview\
		printlen\
		program\
		progress\
		progressbar\
		proofread\
		protex\
		protocol\
		psfragx\
		pstool\
		pstring\
		pxgreeks\
		pygmentex\
		python\
		qstest\
		qsymbols\
		quicktype\
		quotchap\
		quoting\
		quotmark\
		randtext\
		readarray\
		recipe\
		recipebook\
		recipecard\
		refcheck\
		refenums\
		reflectgraphics\
		refman\
		refstyle\
		regcount\
		register\
		regstats\
		relenc\
		repeatindex\
		repltext\
		rjlparshap\
		robustindex\
		romanbar\
		romanbarpagenumber\
		romanneg\
		romannum\
		rotfloat\
		rotpages\
		rterface\
		rtkinenc\
		rulercompass\
		sanitize-umlaut\
		sauerj\
		savefnmark\
		savetrees\
		scalebar\
		scalerel\
		scanpages\
		scrlttr2copy\
		sdrt\
		secdot\
		sectionbox\
		sectionbreak\
		sectsty\
		seealso\
		selectp\
		semantic-markup\
		semantic\
		semioneside\
		semproc\
		sepfootnotes\
		seqsplit\
		sf298\
		sffms\
		sfmath\
		shadethm\
		shadow\
		shadowtext\
		shdoc\
		shipunov\
		shorttoc\
		show2e\
		showcharinbox\
		showdim\
		showexpl\
		sidecap\
		sidenotes\
		silence\
		simplecd\
		simpleinvoice\
		sitem\
		skb\
		skdoc\
		skeyval\
		skrapport\
		slantsc\
		smalltableof\
		smartref\
		smartunits\
		snapshot\
		snotez\
		soul\
		spark-otf\
		sparklines\
		splitindex\
		spotcolor\
		spverbatim\
		srbook-mem\
		srcltx\
		sseq\
		standalone\
		statistik\
		stealcaps\
		stex\
		stringstrings\
		sttools\
		stubs\
		subdepth\
		subeqn\
		subeqnarray\
		subfigmat\
		subfigure\
		subfiles\
		subfloat\
		substitutefont\
		svg\
		svgcolor\
		syntax\
		syntrace\
		synttree\
		tabfigures\
		tableaux\
		tableof\
		tablists\
		tabto-ltx\
		tagging\
		tagpair\
		tamefloats\
		tcldoc\
		tdclock\
		technics\
		ted\
		templatetools\
		termcal\
		termlist\
		testhyphens\
		testidx\
		tex-label\
		texlogos\
		texmate\
		texments\
		texshade\
		textfit\
		textpos\
		textualicomma\
		texvc\
		theoremref\
		thinsp\
		thmtools\
		threadcol\
		thumb\
		thumbs\
		thumby\
		ticket\
		titlecaps\
		titlefoot\
		titlepic\
		titleref\
		titling\
		tocbibind\
		tocdata\
		tocloft\
		tocvsec2\
		todo\
		todonotes\
		tokenizer\
		topfloat\
		totpages\
		trfsigns\
		trivfloat\
		trsym\
		truncate\
		turnthepage\
		twoinone\
		twoup\
		txgreeks\
		type1cm\
		typed-checklist\
		typeface\
		typoaid\
		typogrid\
		uassign\
		umoline\
		underlin\
		underoverlap\
		undolabl\
		units\
		upmethodology\
		upquote\
		uri\
		ushort\
		uspace\
		variablelm\
		varindex\
		varsfromjobname\
		vdmlisting\
		verbasef\
		verbatimcopy\
		verbdef\
		verbments\
		version\
		versions\
		versonotes\
		vertbars\
		vgrid\
		volumes\
		vpe\
		vruler\
		vwcol\
		wallpaper\
		warning\
		was\
		widetable\
		wordcount\
		wordlike\
		wrapfig\
		wtref\
		xbmks \
		xcolor-material\
		xcolor-solarized\
		xdoc\
		xellipsis\
		xhfill\
		xmpincl\
		xnewcommand\
		xoptarg\
		xprintlen\
		xurl\
		xwatermark\
		xytree\
		yafoot\
		yagusylo\
		yaletter\
		ycbook\
		ydoc\
		yplan\
		zebra-goodies\
		zed-csp\
		ziffer\
		zwgetfdate
TEXMF_DOCDIRS=
TEXMF_DOCDIRS_LATEX=	${TEXMF_DIRS_LATEX:Nbeamerthemejltree:Nclasspack:Ndingbat:Neqname:Neulerpx:Nexample:Nfundus-cyr:Nmakedtx:Nmanfnt:Nnestquot:Nnextpage:Nsavesym:Nsfmath:Nspark-otf:Nstack:Ntexlogos:Ntitlefoot:Nvariablelm}

USES=	perl5 python

TEXMF_SHEBANG_FILES=	\
	share/texmf-dist/scripts/shipunov/biokey2html.sh \
	share/texmf-dist/scripts/mycv/mycv_split_contents.pl \
	share/texmf-dist/scripts/changes/pyMergeChanges.py
TEXMF_SHEBANG_FILES_DOCS=	\
	share/doc/texlive-texmf/uspace/uspace-ctanify.sh\
	share/doc/texlive-texmf/shdoc/shreformat.sh\
	share/doc/texlive-texmf/scanpages/replicate.py

post-install-texmf:
	# Part of texlive-bin
.for script in l3build/l3build.lua pax/pdfannotextractor.pl splitindex/splitindex.pl
	${RM} ${STAGEDIR}${LOCALBASE}/share/texmf-dist/scripts/${script}
.endfor

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
