# $FreeBSD$

COMMENT=	Large collection of add-on packages for LaTeX
TEXMF_CATEG=	latexextra

TEXMF_DIRS=	\
	bibtex/bib/attachfile/ bibtex/bib/directory/ bibtex/bib/frankenstein/ \
	bibtex/bib/gloss/ bibtex/bib/glossaries-extra/ bibtex/bib/lsc/ \
	bibtex/bib/msc/ bibtex/bst/achemso/ bibtex/bst/adrconv/ \
	bibtex/bst/chet/ bibtex/bst/datatool/ bibtex/bst/directory/ \
	bibtex/bst/dlfltxb/ bibtex/bst/dvdcoll/ bibtex/bst/frankenstein/ \
	bibtex/bst/gloss/ bibtex/bst/hc/ bibtex/bst/mciteplus/ \
	bibtex/bst/mslapa/ bibtex/bst/opcit/ bibtex/bst/phfnote/ \
	bibtex/bst/savetrees/ bibtex/bst/shipunov/ bibtex/bst/upmethodology/ \
	dvips/esint-type1/ fonts/afm/public/niceframe-type1/ \
	fonts/source/public/casyl/ fonts/source/public/cbcoptic/ \
	fonts/source/public/circ/ fonts/source/public/clock/ \
	fonts/source/public/esint/ fonts/source/public/niceframe/ \
	fonts/tfm/public/casyl/ fonts/tfm/public/cbcoptic/ \
	fonts/tfm/public/circ/ fonts/tfm/public/clock/ \
	fonts/tfm/public/epiolmec/ fonts/tfm/public/esint/ \
	fonts/tfm/public/niceframe/ fonts/tfm/public/relenc/ \
	fonts/tfm/public/scanpages/ fonts/type1/public/cbcoptic/ \
	fonts/type1/public/epiolmec/ fonts/type1/public/esint-type1/ \
	fonts/type1/public/niceframe-type1/ fonts/type1/public/scanpages/ \
	fonts/vf/public/relenc/ makeindex/gmdoc/ makeindex/iso/ \
	makeindex/leipzig/ makeindex/nomencl/ makeindex/nomentbl/ \
	makeindex/repeatindex/ makeindex/xdoc/ metapost/makecirc/ \
	scripts/changes/ scripts/flowfram/ scripts/fmtcount/ scripts/l3build/ \
	scripts/markdown/ scripts/mfirstuc/ scripts/mycv/ scripts/pax/ \
	scripts/shipunov/ scripts/splitindex/ tex/context/third/markdown/ \
	tex/luatex/markdown/ tex/plain/esint-type1/ tex/plain/standalone/

TEXMF_DIRS_GENERIC=	\
	2up filemod formlett markdown minifp poster-mac rlepsf shapepar \
	splitindex textmerg xcomment xint xstring ydoc
TEXMF_DIRS_LATEX=	\
	acro acronym acroterm addfont advdate akktex akletter altfont amsaddr \
	anonchap anyfontsize appendix apptools arcs aurl authorindex autonum \
	avremu bankstatement beton bezos bibletext bigfoot block bold-extra \
	bookest bracketkey breakurl bxcalc bxdvidriver bxnewfont bxtexlogo \
	calrsfs calxxxx-yyyy captcont captdef cases casyl catechis ccaption \
	cclicenses cd cd-cover cdpbundl censor changebar changes chappg \
	chapterfolder chet chextras childdoc chkfloat chletter classics \
	cleveref cmsd codepage colorinfo colorweb combelow combine concprog \
	constants continue coolthms coseoul counttexruns coursepaper \
	crossreference crossreftools crossrefware cutwin cweb-latex cyber \
	cybercic csquotes dashrule dashundergaps dateiliste datenumber \
	datetime datetime2 datetime2-bahasai datetime2-basque \
	datetime2-breton datetime2-bulgarian datetime2-catalan \
	datetime2-croatian datetime2-czech datetime2-danish datetime2-dutch \
	datetime2-en-fulltext datetime2-english datetime2-esperanto \
	datetime2-estonian datetime2-finnish datetime2-french \
	datetime2-galician datetime2-german datetime2-greek datetime2-hebrew \
	datetime2-icelandic datetime2-irish datetime2-it-fulltext \
	datetime2-italian datetime2-latin datetime2-lsorbian datetime2-magyar \
	datetime2-norsk datetime2-polish datetime2-portuges \
	datetime2-romanian datetime2-russian datetime2-samin \
	datetime2-scottish datetime2-serbian datetime2-slovak \
	datetime2-slovene datetime2-spanish datetime2-swedish \
	datetime2-turkish datetime2-ukrainian datetime2-usorbian \
	datetime2-welsh dblfloatfix delimtxt dichokey dinbrief directory \
	dirtytalk dlfltxb dnaseq doclicense docmfp documentation doi dotarrow \
	dox dpfloat draftfigure dynamicnumber easy easyfig easyformat \
	easylist easyreview ebezier ecclesiastic eemeir egplot ellipsis \
	elmath emarks embrac endfloat endheads endnotes envbig envlab \
	epiolmec eqell eqnalign eqname ESIEEcv etextools eukdate eulerpx \
	examplep excludeonly fancynum figsize filecontentsdef fixcmex fixfoot \
	flabels floatflt floatrow fmp fn2end fnbreak fncychap fncylab fnpara \
	fnpct fnumprint fontaxes footmisc footmisx footnotebackref \
	footnoterange footnpag forms16be fragments frankenstein frege ftnxtra \
	fullblck fullminipage fundus-cyr fundus-sueterlin fvextra gcite \
	gender ginpenc gloss glossaries glossaries-danish glossaries-dutch \
	glossaries-english glossaries-extra glossaries-finnish \
	glossaries-french glossaries-german glossaries-irish \
	glossaries-italian glossaries-magyar glossaries-polish \
	glossaries-portuges glossaries-serbian glossaries-spanish gmiflink \
	gmverb graphbox graphicx-psmin grfpaste gridset GS1 guitlogo hang \
	hanging harpoon hc he-she hitec hletter hrefhide hvindex hypdvips \
	hyper hypernat hyperxmp icite idxcmds idxlayout iffont imakeidx \
	indextools interfaces iso iso10303 isodate isonums isopt isorot \
	issuulinks jlabels jumplines jvlisting kerntest keyfloat keyreader \
	kix knowledge koma-script-sfs l3build labels labelschanged latexdemo \
	lazylist lccaps leading lengthconvert lettrine libgreek linegoal \
	lisp-on-tex listing listlbls listofsymbols logical-markup-utils lsc \
	lstaddons ltxdockit ltxindex mailing makedtx makeglos manfnt mathalfa \
	mathfam256 mcite mciteplus memexsupp method mftinc minorrevision \
	minutes modref modular monofill morefloats morehype moresize moreverb \
	morewrites mparhack mpostinl msg mtgreek multibbl multicap multilang \
	mversion mwe mylatexformat nameauth ncclatex ncctools nestquot \
	newunicodechar newvbtm newverbs nfssext-cfr niceframe nicetext \
	nidanfloat nlctdoc nolbreaks nomencl nomentbl nonfloat nopageno \
	normalcolor notes notespages notoccite ntheorem numberedblock \
	ocr-latex oldstyle onlyamsmath opcit optional outliner outlining \
	pagecolor pagecont pagenote pageslts papermas parades paresse \
	parnotes pauldoc pecha phffullpagefigure phfnote phfquotetext phfthm \
	philex photo piff placeins plantslabels plates plweb preprint \
	prettyref preview printlen protex protocol pxgreeks qstest quicktype \
	quotchap quoting quotmark randtext readarray refenums refman refstyle \
	relenc rjlparshap robustindex romanneg rotfloat rotpages rtkinenc \
	sanitize-umlaut sauerj savefnmark scalebar scalerel scanpages secdot \
	sectionbox sectionbreak sectsty selectp semproc sepfootnotes seqsplit \
	sfmath shadethm shipunov shorttoc show2e showcharinbox showdim \
	showexpl sidecap sidenotes skrapport slantsc smalltableof smartref \
	snapshot snotez soul splitindex spverbatim srbook-mem srcltx \
	statistik stealcaps stex sttools substitutefont syntax Tabbing \
	tableof tabto-ltx tagpair tamefloats tcldoc technics termlist \
	testhyphens tex-label texlogos textpos theoremref thinsp thmtools \
	thumb thumbs thumby titlecaps titlefoot titlepic titleref tocbibind \
	tocdata tocloft tocvsec2 tokenizer topfloat trivfloat turnthepage \
	twoup txgreeks type1cm typeface typoaid typogrid underlin upquote \
	uspace variablelm varindex vdmlisting verbasef verbatimcopy verbdef \
	version versions versonotes vgrid volumes vpe vruler warning wtref \
	xbmks xcolor-material xcolor-solarized xdoc xprintlen xurl yafoot \
	ycbook yplan zed-csp
TEXMF_DOCDIRS=
TEXMF_DOCDIRS_LATEX=	${TEXMF_DIRS_LATEX:Nbeamerthemejltree:Nclasspack:Neqname:Neulerpx:Nexample:Nfundus-cyr:Nmakedtx:Nmanfnt:Nnestquot:Nnextpage:Nsavesym:Nsfmath:Nstack:Ntexlogos:Ntitlefoot:Nvariablelm:Ncrossrefware}

USES=	perl5 python

TEXMF_SHEBANG_FILES=	\
	share/texmf-dist/scripts/shipunov/biokey2html.sh \
	share/texmf-dist/scripts/mycv/mycv_split_contents.pl \
	share/texmf-dist/scripts/changes/pyMergeChanges.py
TEXMF_SHEBANG_FILES_DOCS=	\
	share/doc/texlive-texmf/uspace/uspace-ctanify.sh\
	share/doc/texlive-texmf/scanpages/replicate.py

post-install-texmf:
	# Part of texlive-bin
.for script in l3build/l3build.lua pax/pdfannotextractor.pl splitindex/splitindex.pl
	${RM} ${STAGEDIR}${LOCALBASE}/share/texmf-dist/scripts/${script}
.endfor

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
