# $FreeBSD$

COMMENT=	Many extra fonts
TEXMF_CATEG=	fonts-extra
TEXMF_DIRS=	\
	dvips/initials/ tex/context/third/gentium-tug/ \
	tex/context/third/semaphor/ tex/generic/ean/ tex/generic/mathabx/ \
	tex/plain/ly1/ tex/plain/semaphor/
TEXMF_DIRS_FONTS=	\
	afm/arkandis/adforn/ afm/esstix/ afm/public/archaic/ \
	afm/public/augie/ afm/public/bbold-type1/ afm/public/carolmin-ps/ \
	afm/public/cm-lgc/ afm/public/cm-unicode/ afm/public/cmsrb/ \
	afm/public/countriesofeurope/ afm/public/dozenal/ \
	afm/public/dutchcal/ afm/public/fonetika/ afm/public/gentium-tug/ \
	afm/public/gfscomplutum/ afm/public/gfssolomos/ afm/public/hfbright/ \
	afm/public/initials/ afm/public/linearA/ afm/public/old-arrows/ \
	afm/public/phaistos/ afm/public/prodint/ afm/public/semaphor/ \
	afm/public/starfont/ afm/public/svrsymbols/ afm/public/tempora/ \
	afm/public/tfrupee/ afm/public/trajan/ enc/dvips/adforn/ \
	enc/dvips/b1encoding/ enc/dvips/cfr-lm/ enc/dvips/cinzel/ \
	enc/dvips/cm-lgc/ enc/dvips/cm-unicode/ enc/dvips/cmsrb/ \
	enc/dvips/countriesofeurope/ enc/dvips/dantelogo/ \
	enc/dvips/ebgaramond-maths/ enc/dvips/ebgaramond/ \
	enc/dvips/gentium-tug/ enc/dvips/gfscomplutum/ enc/dvips/gfssolomos/ \
	enc/dvips/hfbright/ enc/dvips/ly1/ enc/dvips/mnsymbol/ \
	enc/dvips/old-arrows/ enc/dvips/semaphor/ enc/dvips/tempora/ \
	enc/dvips/tengwarscript/ enc/dvips/tinos/ ofm/public/cm-lgc/ \
	opentype/public/almfixed/ opentype/public/beuron/ \
	opentype/public/cm-unicode/ opentype/public/dantelogo/ \
	opentype/public/ebgaramond/ opentype/public/fonts-churchslavonic/ \
	opentype/public/gfscomplutum/ opentype/public/gfssolomos/ \
	opentype/public/gnu-freefont/ opentype/public/mnsymbol/ \
	opentype/public/ocr-b-outline/ opentype/public/phaistos/ \
	opentype/public/punknova/ opentype/public/semaphor/ \
	opentype/public/tempora/ opentype/public/umtypewriter/ \
	opentype/public/yinit-otf/ ovf/public/cm-lgc/ source/public/allrunes/ \
	source/public/archaic/ source/public/aspectratio/ \
	source/public/astro/ source/public/barcodes/ source/public/bbm/ \
	source/public/bbold/ source/public/beuron/ source/public/bguq/ \
	source/public/cherokee/ source/public/cm-mf-extra-bold/ \
	source/public/cmbright/ source/public/cmll/ source/public/cmtiup/ \
	source/public/dancers/ source/public/dice/ \
	source/public/doublestroke/ source/public/dozenal/ \
	source/public/duerer/ source/public/ecc/ source/public/elvish/ \
	source/public/esrelation/ source/public/euxm/ source/public/feyn/ \
	source/public/fge/ source/public/gothic/ source/public/greenpoint/ \
	source/public/jablantile/ source/public/kixfont/ source/public/lfb/ \
	source/public/lxfonts/ source/public/mathabx/ source/public/mnsymbol/ \
	source/public/ocr-b/ source/public/ogham/ source/public/orkhun/ \
	source/public/pacioli/ source/public/phonetic/ source/public/pigpen/ \
	source/public/punk/ source/public/recycle/ \
	source/public/sansmathfonts/ source/public/sauter/ \
	source/public/semaphor/ source/public/semaphor/metafont/ \
	source/public/skull/ source/public/universa/ source/public/wsuipa/ \
	tfm/adobe/ly1/ tfm/arkandis/adforn/ tfm/google/tinos tfm/ndiscovered/ \
	tfm/public/aecc/ tfm/public/archaic/ tfm/public/aspectratio/ \
	tfm/public/astro/ tfm/public/augie/ tfm/public/barcodes/ \
	tfm/public/bbm/ tfm/public/bbold/ tfm/public/beuron/ tfm/public/bguq/ \
	tfm/public/blacklettert1/ tfm/public/boondox/ tfm/public/cfr-lm/ \
	tfm/public/cherokee/ tfm/public/cm-lgc/ tfm/public/cm-mf-extra-bold/ \
	tfm/public/cmbright/ tfm/public/cmexb/ tfm/public/cmll/ \
	tfm/public/cmsrb/ tfm/public/cmtiup/ tfm/public/countriesofeurope/ \
	tfm/public/dancers/ tfm/public/dantelogo/ tfm/public/dice/ \
	tfm/public/doublestroke/ tfm/public/dozenal/ tfm/public/duerer/ \
	tfm/public/dutchcal/ tfm/public/ebgaramond-maths/ \
	tfm/public/ebgaramond/ tfm/public/ecc/ tfm/public/eco/ \
	tfm/public/elvish/ tfm/public/esrelation/ tfm/public/esstix/ \
	tfm/public/eulervm/ tfm/public/euxm/ tfm/public/feyn/ tfm/public/fge/ \
	tfm/public/foekfont/ tfm/public/fonetika/ tfm/public/gentium-tug/ \
	tfm/public/gfscomplutum/ tfm/public/gfssolomos/ tfm/public/gillcm/ \
	tfm/public/gothic/ tfm/public/greenpoint/ tfm/public/hacm/ \
	tfm/public/hfoldsty/ tfm/public/initials/ tfm/public/ipaex-type1/ \
	tfm/public/jamtimes/ tfm/public/kixfont/ tfm/public/lfb/ \
	tfm/public/linearA/ tfm/public/lxfonts/ tfm/public/mathabx/ \
	tfm/public/mdputu/ tfm/public/mnsymbol/ tfm/public/ocr-b/ \
	tfm/public/ogham/ tfm/public/old-arrows/ tfm/public/orkhun/ \
	tfm/public/pacioli/ tfm/public/phaistos/ tfm/public/phonetic/ \
	tfm/public/pigpen/ tfm/public/prodint/ tfm/public/punk/ \
	tfm/public/pxtxalfa/ tfm/public/recycle/ tfm/public/rsfso/ \
	tfm/public/sansmathaccent/ tfm/public/sansmathfonts/ \
	tfm/public/semaphor/ tfm/public/starfont/ tfm/public/staves/ \
	tfm/public/svrsymbols/ tfm/public/tempora/ tfm/public/tengwarscript/ \
	tfm/public/tfrupee/ tfm/public/trajan/ tfm/public/txuprcal/ \
	tfm/public/universa/ tfm/public/uppunctlm/ tfm/public/wsuipa/ \
	tfm/urw/urwchancal/ truetype/google/tinos/ truetype/ndiscovered/ \
	truetype/ndiscovered/cinzel/ truetype/public/almfixed/ \
	truetype/public/belleek/ truetype/public/fonetika/ \
	truetype/public/fonts-churchslavonic/ truetype/public/gentium-tug/ \
	truetype/public/gnu-freefont/ type1/arkandis/adforn/ \
	type1/google/tinos/ type1/ndiscovered/cinzel/ type1/public/allrunes/ \
	type1/public/archaic/ type1/public/aspectratio/ type1/public/augie/ \
	type1/public/bbold-type1/ type1/public/belleek/ type1/public/beuron/ \
	type1/public/bguq/ type1/public/boondox/ type1/public/carolmin-ps/ \
	type1/public/cm-lgc/ type1/public/cm-unicode/ type1/public/cmexb/ \
	type1/public/cmll/ type1/public/cmsrb/ \
	type1/public/countriesofeurope/ type1/public/dantelogo/ \
	type1/public/doublestroke/ type1/public/dozenal/ \
	type1/public/dutchcal/ type1/public/ebgaramond/ \
	type1/public/esrelation/ type1/public/esstix/ type1/public/fge/ \
	type1/public/foekfont/ type1/public/fonetika/ \
	type1/public/gentium-tug/ type1/public/gfscomplutum/ \
	type1/public/gfssolomos/ type1/public/hacm/ type1/public/hfbright/ \
	type1/public/initials/ type1/public/ipaex-type1/ \
	type1/public/linearA/ type1/public/lxfonts/ \
	type1/public/mathabx-type1/ type1/public/mnsymbol/ \
	type1/public/ocr-b-outline/ type1/public/old-arrows/ \
	type1/public/phaistos/ type1/public/pigpen/ type1/public/prodint/ \
	type1/public/recycle/ type1/public/sansmathfonts/ \
	type1/public/semaphor/ type1/public/starfont/ type1/public/staves/ \
	type1/public/svrsymbols/ type1/public/tempora/ type1/public/tfrupee/ \
	type1/public/trajan/ type1/public/txuprcal/ vf/adobe/ly1/ \
	vf/google/tinos/ vf/ndiscovered/cinzel/ vf/public/aecc/ \
	vf/public/augie/ vf/public/blacklettert1/ vf/public/boondox/ \
	vf/public/cfr-lm/ vf/public/cm-lgc/ vf/public/cmsrb/ \
	vf/public/cmtiup/ vf/public/dantelogo/ vf/public/dutchcal/ \
	vf/public/ebgaramond/ vf/public/eco/ vf/public/esstix/ \
	vf/public/eulervm/ vf/public/gfscomplutum/ vf/public/gfssolomos/ \
	vf/public/gillcm/ vf/public/hacm/ vf/public/hfoldsty/ \
	vf/public/jamtimes/ vf/public/mdputu/ vf/public/pxtxalfa/ \
	vf/public/rsfso/ vf/public/sansmathaccent/ vf/public/sansmathfonts/ \
	vf/public/tempora/ vf/public/tengwarscript/ vf/public/uppunctlm/ \
	vf/urw/urwchancal/
TEXMF_DIRS_LATEX=	\
	adforn aecc allrunes archaic aspectratio augie b1encoding barcodes \
	bbm-macros bbold beuron bguq blacklettert1 boondox braille \
	cfr-initials cfr-lm cherokee cinzel cm-lgc cmbright cmll cmsrb cmtiup \
	countriesofeurope courier-scaled dantelogo doublestroke dozenal \
	duerer-latex dutchcal ebgaramond ebgaramond-maths eco epsdice \
	esrelation esstix eulervm feyn fge foekfont fonetika gentium-tug \
	gfscomplutum gfssolomos gillcm hacm hfoldsty initials ipaex-type1 \
	jamtimes linearA lxfonts ly1 mdputu mnsymbol mweights old-arrows \
	pacioli phaistos phonetic pigpen prodint punk-latex pxtxalfa recycle \
	rsfso sansmathaccent sansmathfonts sauterfonts semaphor skull \
	starfont staves svrsymbols tempora tengwarscript tfrupee tinos \
	tpslifonts trajan txuprcal universa uppunctlm urwchancal wsuipa zlmtt
TEXMF_DOCDIRS_LATEX=	\
	aspectratio augie b1encoding barcodes bbm-macros \
	bbm-macros bbold braille cfr-initials cmtiup \
	duerer-latex epsdice eulervm \
	foekfont gillcm jamtimes mdputu mnsymbol mweights \
	pigpen punk-latex sauterfonts tengwarscript tpslifonts trajan
TEXMF_DOCDIRS_FONTS=	${TEXMF_DIRS_LATEX:Nskull}
.for nd in ${TEXMF_DOCDIRS_LATEX}
TEXMF_DOCDIRS_FONTS:=	${TEXMF_DOCDIRS_FONTS:N${nd}}
.endfor

TEXMF_SHEBANG_FILES_DOCS=	share/doc/texlive-texmf/phaistos/getglyphs

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
