# $FreeBSD$

COMMENT=	Packages for creating boxes
TEXMF_CATEG=	boxing

TEXMF_DIRS=	\
	metapost/roundrect tex/generic/frame
TEXMF_DIRS_LATEX=	\
	adjustbox alertmessage awesomebox boites boxedminipage \
	boxedminipage2e boxhandler capt-of collectbox crbox dashbox efbox \
	eqparbox fancybox framed genmpage ghab graphicxbox longfbox makebox \
	mdframed minibox minipage-marginpar pbox realboxes roundbox tcolorbox \
	tram varwidth verbatimbox xsavebox

TEXMF_DOCDIRS=	generic/frame
TEXMF_DOCDIRS_LATEX=	${TEXMF_DIRS_LATEX}

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
