# $FreeBSD$

COMMENT=	Serif and Sans Serif fonts
TEXMF_CATEG=	fonts-serif

TEXMF_DIRS=	\
	dvips/mathdesign/ metapost/fetamont/ tex/plain/antt/ tex/plain/iwona/ \
	tex/plain/kurier/
TEXMF_DIRS_FONTS=	\
	afm/arkandis/baskervald/ afm/arkandis/berenisadf/ \
	afm/arkandis/electrum/ afm/arkandis/libris/ afm/arkandis/romande/ \
	afm/arkandis/venturis/ afm/arkandis/venturis2/ \
	afm/arkandis/venturisold/ afm/arkandis/venturissans/ \
	afm/arkandis/venturissans2/ afm/gust/poltawski/ afm/nowacki/iwona/ \
	afm/nowacki/kurier/ afm/paratype/ afm/public/antt/ afm/public/arev/ \
	afm/public/baskervaldx/ afm/public/cantarell/ afm/public/cantarell/ \
	afm/public/cochineal/ afm/public/comfortaa/ afm/public/cyklop/ \
	afm/public/dejavu/ afm/public/drm/ afm/public/droid/ \
	afm/public/epigrafica/ afm/public/erewhon/ afm/public/fetamont/ \
	afm/public/fourier/ afm/public/fouriernc/ afm/public/gfsartemisia/ \
	afm/public/gfsbodoni/ afm/public/gfsdidot/ afm/public/gfsneohellenic/ \
	afm/public/libertinust1math/ afm/public/newpx/ afm/public/newtx/ \
	afm/public/nimbus15/ afm/public/opensans/ afm/public/stickstoo \
	afm/public/txfontsb/ afm/public/xcharter/ afm/urw/antiqua/ \
	afm/urw/grotesq/ enc/dvips/accanthis/ enc/dvips/alegreya/ \
	enc/dvips/algolrevived/ enc/dvips/antt/ enc/dvips/arev/ \
	enc/dvips/arimo/ enc/dvips/baskervald/ enc/dvips/baskervaldx/ \
	enc/dvips/baskervillef/ enc/dvips/berenisadf/ enc/dvips/cabin/ \
	enc/dvips/caladea/ enc/dvips/cantarell/ enc/dvips/carlito/ \
	enc/dvips/chivo/ enc/dvips/clearsans/ enc/dvips/cochineal/ \
	enc/dvips/coelacanth/ enc/dvips/comfortaa/ enc/dvips/comicneue/ \
	enc/dvips/cormorantgaramond/ enc/dvips/crimson/ enc/dvips/cyklop/ \
	enc/dvips/dejavu/ enc/dvips/droid/ enc/dvips/electrum/ \
	enc/dvips/epigrafica/ enc/dvips/erewhon/ enc/dvips/fbb/ \
	enc/dvips/fira/ enc/dvips/gfsartemisia/ enc/dvips/gfsbodoni/ \
	enc/dvips/gfsdidot/ enc/dvips/gfsneohellenic/ enc/dvips/gillius/ \
	enc/dvips/gofonts/ enc/dvips/heuristica/ enc/dvips/imfellenglish/ \
	enc/dvips/inriafonts enc/dvips/iwona/ enc/dvips/kurier/ \
	enc/dvips/lato/ enc/dvips/libertine/ enc/dvips/libertinegc/ \
	enc/dvips/libertinus-type1/ enc/dvips/libertinust1math/ \
	enc/dvips/librebaskerville/ enc/dvips/librebodoni/ \
	enc/dvips/librecaslon/ enc/dvips/libris/ enc/dvips/mathdesign/ \
	enc/dvips/merriweather/ enc/dvips/mintspirit/ enc/dvips/montserrat/ \
	enc/dvips/newpx/ enc/dvips/newtx/ enc/dvips/nimbus15/ enc/dvips/noto/ \
	enc/dvips/oldstandard/ enc/dvips/opensans/ enc/dvips/overlock/ \
	enc/dvips/paratype/ enc/dvips/playfair/ enc/dvips/plex/ \
	enc/dvips/poltawski/ enc/dvips/quattrocento/ enc/dvips/raleway/ \
	enc/dvips/roboto/ enc/dvips/romande/ enc/dvips/rosario/ \
	enc/dvips/sourcesanspro/ enc/dvips/sourceserifpro/ \
	enc/dvips/stickstoo enc/dvips/stix/ enc/dvips/txfontsb/ \
	enc/dvips/universalis/ enc/dvips/venturisadf/ enc/dvips/xcharter/ \
	opentype/adobe/sourcesanspro/ opentype/adobe/sourceserifpro/ \
	opentype/arkandis/accanthis/ opentype/arkandis/berenisadf/ \
	opentype/arkandis/gillius/ opentype/arkandis/mintspirit/ \
	opentype/arkandis/universalis/ opentype/catharsis/cormorantgaramond/ \
	opentype/google/noto/ opentype/gust/poltawski/ \
	opentype/huerta/alegreya/ opentype/ibm/plex/ \
	opentype/iginomarini/imfellenglish/ opentype/impallari/cabin/ \
	opentype/impallari/librebaskerville/ opentype/impallari/librebodoni/ \
	opentype/impallari/librecaslon/ opentype/impallari/quattrocento/ \
	opentype/impallari/raleway/ opentype/kosch/crimson/ \
	opentype/nowacki/iwona/ opentype/nowacki/kurier/ \
	opentype/public/algolrevived/ opentype/public/antt/ \
	opentype/public/Asana-Math/ opentype/public/baskervaldx/ \
	opentype/public/baskervillef/ opentype/public/chivo/ \
	opentype/public/cochineal/ opentype/public/coelacanth/ \
	opentype/public/cyklop/ opentype/public/drm/ opentype/public/erewhon/ \
	opentype/public/fbb/ opentype/public/fetamont/ opentype/public/fira/ \
	opentype/public/gfsartemisia/ opentype/public/gfsbodoni/ \
	opentype/public/gfsdidot/ opentype/public/gfsneohellenic/ \
	opentype/public/gfsneohellenicmath/ opentype/public/heuristica/ \
	opentype/public/inriafonts opentype/public/libertine/ \
	opentype/public/montserrat/ opentype/public/newpx/ \
	opentype/public/newtx/ opentype/public/nimbus15/ \
	opentype/public/oldstandard/ opentype/public/playfair/ \
	opentype/public/rosario/ opentype/public/shobhika/ \
	opentype/public/stix/ opentype/public/xcharter/ opentype/public/xits/ \
	source/public/boisik/ source/public/concmath-fonts/ \
	source/public/drm/ source/public/fetamont/ source/public/obnov/ \
	source/public/oldlatin/ source/public/tapir/ tfm/adobe/sourcesanspro/ \
	tfm/adobe/sourceserifpro/ tfm/arkandis/accanthis/ \
	tfm/arkandis/baskervald/ tfm/arkandis/berenisadf/ \
	tfm/arkandis/electrum/ tfm/arkandis/gillius/ tfm/arkandis/libris/ \
	tfm/arkandis/mintspirit/ tfm/arkandis/romande/ \
	tfm/arkandis/universalis/ tfm/arkandis/venturis/ \
	tfm/arkandis/venturis2/ tfm/arkandis/venturisold/ \
	tfm/arkandis/venturissans/ tfm/arkandis/venturissans2/ \
	tfm/catharsis/cormorantgaramond/ tfm/intel/clearsans/ \
	tfm/kosch/crimson/ tfm/paratype/ tfm/public/algolrevived/ \
	tfm/public/antt/ tfm/public/arev/ tfm/public/baskervaldx/ \
	tfm/public/baskervillef/ tfm/public/boisik/ tfm/public/cantarell/ \
	tfm/public/chivo/ tfm/public/cochineal/ tfm/public/coelacanth/ \
	tfm/public/comfortaa/ tfm/public/concmath-fonts/ tfm/public/cyklop/ \
	tfm/public/dejavu/ tfm/public/drm/ tfm/public/droid/ \
	tfm/public/epigrafica/ tfm/public/erewhon/ tfm/public/fbb/ \
	tfm/public/fetamont/ tfm/public/fira/ tfm/public/fourier/ \
	tfm/public/fouriernc/ tfm/public/gfsartemisia/ tfm/public/gfsbodoni/ \
	tfm/public/gfsdidot/ tfm/public/gfsneohellenic/ \
	tfm/public/heuristica/ tfm/public/inriafonts tfm/public/libertine/ \
	tfm/public/libertinegc/ tfm/public/libertinus-type1/ \
	tfm/public/libertinust1math/ tfm/public/mathdesign/ \
	tfm/public/mathdesign/mdbch/ tfm/public/mathdesign/mdgreek/ \
	tfm/public/mathdesign/mdici/ tfm/public/mathdesign/mdpgd/ \
	tfm/public/mathdesign/mdpus/ tfm/public/mathdesign/mdput/ \
	tfm/public/mathdesign/mdugm/ tfm/public/montserrat/ tfm/public/newpx/ \
	tfm/public/newtx/ tfm/public/newtxsf/ tfm/public/nimbus15/ \
	tfm/public/obnov/ tfm/public/oldlatin/ tfm/public/oldstandard/ \
	tfm/public/opensans/ tfm/public/playfair/ tfm/public/rosario/ \
	tfm/public/stickstoo tfm/public/stix/ tfm/public/txfontsb/ \
	tfm/public/xcharter/ tfm/rozynski/comicneue/ tfm/sorkin/merriweather/ \
	tfm/typoland/carlito/ tfm/typoland/lato/ tfm/urw/antiqua/ \
	tfm/urw/grotesq/ truetype/bh/gofonts/ truetype/google/arimo/ \
	truetype/huerta/caladea/ truetype/intel/clearsans/ \
	truetype/muhafara/overlock/ truetype/paratype/ \
	truetype/public/Asana-Math/ truetype/public/comfortaa/ \
	truetype/public/dejavu/ truetype/public/droid/ \
	truetype/public/inriafonts truetype/public/junicode/ \
	truetype/public/opensans/ truetype/sorkin/merriweather/ \
	truetype/typoland/carlito/ truetype/typoland/lato/ \
	type1/adobe/sourcesanspro/ type1/adobe/sourceserifpro/ \
	type1/arkandis/accanthis/ type1/arkandis/baskervald/ \
	type1/arkandis/berenisadf/ type1/arkandis/electrum/ \
	type1/arkandis/gillius/ type1/arkandis/libris/ \
	type1/arkandis/mintspirit/ type1/arkandis/romande/ \
	type1/arkandis/universalis/ type1/arkandis/venturis/ \
	type1/arkandis/venturis2/ type1/arkandis/venturisold/ \
	type1/arkandis/venturissans/ type1/arkandis/venturissans2/ \
	type1/bh/gofonts/ type1/catharsis/cormorantgaramond/ \
	type1/google/arimo/ type1/google/noto/ type1/google/roboto/ \
	type1/gust/poltawski/ type1/huerta/alegreya/ type1/huerta/caladea/ \
	type1/ibm/plex/ type1/iginomarini/imfellenglish/ \
	type1/impallari/cabin/ type1/impallari/librebaskerville/ \
	type1/impallari/librebodoni/ type1/impallari/librecaslon/ \
	type1/impallari/quattrocento/ type1/impallari/raleway/ \
	type1/intel/clearsans/ type1/kosch/crimson/ type1/muhafara/overlock/ \
	type1/nowacki/iwona/ type1/nowacki/kurier/ type1/paratype/ptmono/ \
	type1/paratype/ptsans/ type1/paratype/ptserif/ \
	type1/public/algolrevived/ type1/public/antt/ type1/public/arev/ \
	type1/public/baskervaldx/ type1/public/baskervillef/ \
	type1/public/cantarell/ type1/public/chivo/ type1/public/cochineal/ \
	type1/public/coelacanth/ type1/public/comfortaa/ type1/public/cyklop/ \
	type1/public/dejavu/ type1/public/drm/ type1/public/droid/ \
	type1/public/epigrafica/ type1/public/erewhon/ type1/public/fbb/ \
	type1/public/fetamont/ type1/public/fira/ type1/public/fourier/ \
	type1/public/gfsartemisia/ type1/public/gfsbodoni/ \
	type1/public/gfsdidot/ type1/public/gfsneohellenic/ \
	type1/public/heuristica/ type1/public/inriafonts \
	type1/public/libertine/ type1/public/libertinus-type1/ \
	type1/public/libertinust1math/ type1/public/mathdesign/ \
	type1/public/mathdesign/mdbch/ type1/public/mathdesign/mdici/ \
	type1/public/mathdesign/mdpgd/ type1/public/mathdesign/mdpus/ \
	type1/public/mathdesign/mdput/ type1/public/mathdesign/mdugm/ \
	type1/public/montserrat/ type1/public/newpx/ type1/public/newtx/ \
	type1/public/newtxsf/ type1/public/nimbus15/ \
	type1/public/oldstandard/ type1/public/opensans/ \
	type1/public/playfair/ type1/public/rosario/ type1/public/stickstoo \
	type1/public/stix/ type1/public/tapir/ type1/public/txfontsb/ \
	type1/public/xcharter/ type1/rozynski/comicneue/ \
	type1/sorkin/merriweather/ type1/typoland/carlito/ \
	type1/typoland/lato/ type1/urw/antiqua/ type1/urw/grotesq/ \
	vf/adobe/sourcesanspro/ vf/adobe/sourceserifpro/ \
	vf/arkandis/accanthis/ vf/arkandis/baskervald/ vf/arkandis/electrum/ \
	vf/arkandis/gillius/ vf/arkandis/libris/ vf/arkandis/mintspirit/ \
	vf/arkandis/romande/ vf/arkandis/universalis/ vf/arkandis/venturis/ \
	vf/arkandis/venturis2/ vf/arkandis/venturisold/ \
	vf/arkandis/venturissans/ vf/arkandis/venturissans2/ vf/bh/gofonts/ \
	vf/catharsis/cormorantgaramond/ vf/google/arimo/ vf/google/noto/ \
	vf/google/roboto/ vf/huerta/alegreya/ vf/huerta/caladea/ vf/ibm/plex/ \
	vf/iginomarini/imfellenglish/ vf/impallari/cabin/ \
	vf/impallari/librebaskerville/ vf/impallari/librebodoni/ \
	vf/impallari/librecaslon/ vf/impallari/quattrocento/ \
	vf/impallari/raleway/ vf/intel/clearsans/ vf/kosch/crimson/ \
	vf/muhafara/overlock/ vf/paratype/ptmono/ vf/paratype/ptsans/ \
	vf/paratype/ptserif/ vf/public/algolrevived/ vf/public/arev/ \
	vf/public/baskervaldx/ vf/public/baskervillef/ vf/public/cantarell/ \
	vf/public/chivo/ vf/public/cochineal/ vf/public/coelacanth/ \
	vf/public/comfortaa/ vf/public/dejavu/ vf/public/droid/ \
	vf/public/epigrafica/ vf/public/erewhon/ vf/public/fbb/ \
	vf/public/fira/ vf/public/fourier/ vf/public/fouriernc/ \
	vf/public/gfsartemisia/ vf/public/gfsbodoni/ vf/public/gfsdidot/ \
	vf/public/gfsneohellenic/ vf/public/heuristica/ vf/public/inriafonts \
	vf/public/libertine/ vf/public/libertinus-type1/ \
	vf/public/libertinust1math/ vf/public/mathdesign/ \
	vf/public/mathdesign/mdbch/ vf/public/mathdesign/mdgreek/ \
	vf/public/mathdesign/mdici/ vf/public/mathdesign/mdpgd/ \
	vf/public/mathdesign/mdpus/ vf/public/mathdesign/mdput/ \
	vf/public/mathdesign/mdugm/ vf/public/montserrat/ vf/public/newpx/ \
	vf/public/newtx/ vf/public/newtxsf/ vf/public/nimbus15/ \
	vf/public/oldstandard/ vf/public/opensans/ vf/public/playfair/ \
	vf/public/rosario/ vf/public/stickstoo vf/public/stix/ \
	vf/public/txfontsb/ vf/public/xcharter/ vf/rozynski/comicneue/ \
	vf/sorkin/merriweather/ vf/typoland/carlito/ vf/typoland/lato/ \
	vf/urw/antiqua/ vf/urw/grotesq/

TEXMF_DIRS_LATEX=	\
	accanthis alegreya algolrevived antiqua antt arev arimo baskervald \
	baskervaldx baskervillef berenisadf boisik cabin caladea cantarell \
	carlito chivo clearsans cochineal coelacanth comfortaa comicneue \
	concmath cormorantgaramond crimson cyklop dejavu dejavu-otf drm droid \
	electrum epigrafica erewhon fbb fetamont fira fourier fouriernc \
	gfsartemisia gfsbodoni gfsdidot gfsneohellenic gfsneohellenicmath \
	gillius gofonts grotesq heuristica imfellenglish inriafonts iwona \
	junicode kurier lato libertine libertinegc libertinus-type1 \
	libertinust1math librebaskerville librebodoni librecaslon libris \
	mathdesign merriweather mintspirit montserrat newpx newtx newtxsf \
	nimbus15 noto obnov oldstandard opensans overlock paratype playfair \
	plex plex-otf poltawski quattrocento raleway roboto romande rosario \
	sourcesanspro sourceserifpro stickstoo stix stix2 txfontsb \
	universalis venturis venturis2 venturisadf venturisold venturissans \
	venturissans2 xcharter
TEXMF_DOCDIRS_LATEX=	comicneue raleway sourcesanspro sourceserifpro stix2
TEXMF_DOCDIRS_FONTS=	${TEXMF_DIRS_LATEX} stickstoo libertinus-type1
.for nd in ${TEXMF_DOCDIRS_LATEX} venturis venturis2 venturisadf venturisold \
	venturissans venturissans2
TEXMF_DOCDIRS_FONTS:=${TEXMF_DOCDIRS_FONTS:N${nd}}
.endfor

DOCS_USES+=	python

SHEBANG_LANG+=	fontforge
fontforge_OLD_CMD=	/usr/bin/fontforge
fontforge_CMD=	${LOCALBASE}/bin/fontforge
TEXMF_SHEBANG_FILES_DOCS=	share/doc/texlive-texmf/berenisadf/ff-ybd.pe \
				share/doc/texlive-texmf/drm/allfonts.sh \
				share/doc/texlive-texmf/xcharter/altone.py

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
