# $FreeBSD$

COMMENT=	Base LaTeX packages and fonts
TEXMF_CATEG=	base
TEXMF_DIRS=	\
	bibtex/bib/abstyles/ bibtex/bib/base/ bibtex/bib/gustlib/ \
	bibtex/bib/oberdiek/ bibtex/bst/abstyles/ bibtex/bst/amscls/ \
	bibtex/bst/apalike-german/ bibtex/bst/babelbib/ bibtex/bst/base/ \
	bibtex/bst/bib-fr/ bibtex/bst/cnbwp/ bibtex/bst/context/ \
	bibtex/bst/context/mkii/ bibtex/bst/dinat/ bibtex/bst/finbib/ \
	bibtex/bst/germbib/ bibtex/bst/gustlib/ bibtex/bst/index/ \
	bibtex/bst/natbib/ bibtex/bst/przechlewski-book/ bibtex/bst/swebib/ \
	bibtex/bst/udesoftec/ bibtex/csf/polish-csf/ chktex/ \
	context/data/npp/ context/data/npp/context/ context/data/scite/ \
	context/data/texfont/ context/data/textadept/ context/data/texworks/ \
	dvipdfmx/ dvips/avantgar/ dvips/bookman/ dvips/cm-super/ \
	dvips/colorsep/ dvips/config/ dvips/courier/ dvips/dvipsconfig/ \
	dvips/garuda-c90/ dvips/getafm/ dvips/helvetic/ dvips/ncntrsbk/ \
	dvips/norasi-c90/ dvips/palatino/ dvips/pl/ dvips/psfrag/ \
	dvips/pspicture/ dvips/symbol/ dvips/tetex/ dvips/tex-ps/ \
	dvips/times/ dvips/xcolor/ dvips/zapfchan/ dvips/zapfding/ \
	fonts/afm/adobe/avantgar/ fonts/afm/adobe/bookman/ \
	fonts/afm/adobe/courier/ fonts/afm/adobe/helvetic/ \
	fonts/afm/adobe/ncntrsbk/ fonts/afm/adobe/palatino/ \
	fonts/afm/adobe/symbol/ fonts/afm/adobe/times/ \
	fonts/afm/adobe/utopia/ fonts/afm/adobe/zapfchan/ \
	fonts/afm/adobe/zapfding/ fonts/afm/bitstrea/charter/ \
	fonts/afm/hoekwater/ fonts/afm/jmn/ fonts/afm/metapost/ \
	fonts/afm/public/amsfonts/cm/ fonts/afm/public/amsfonts/cmextra/ \
	fonts/afm/public/amsfonts/cyrillic/ fonts/afm/public/amsfonts/euler/ \
	fonts/afm/public/amsfonts/latxfont/ \
	fonts/afm/public/amsfonts/symbols/ fonts/afm/public/armenian/ \
	fonts/afm/public/cm-super/ fonts/afm/public/fpl/ fonts/afm/public/lm/ \
	fonts/afm/public/mathpazo/ fonts/afm/public/pl/ \
	fonts/afm/public/pxfonts/ fonts/afm/public/rsfs/ \
	fonts/afm/public/tabvar/ fonts/afm/public/tex-gyre/ \
	fonts/afm/public/txfonts/ fonts/afm/public/wasy2-ps/ \
	fonts/afm/urw/avantgar/ fonts/afm/urw/bookman/ fonts/afm/urw/courier/ \
	fonts/afm/urw/helvetic/ fonts/afm/urw/ncntrsbk/ \
	fonts/afm/urw/palatino/ fonts/afm/urw/symbol/ fonts/afm/urw/times/ \
	fonts/afm/urw/zapfchan/ fonts/afm/urw/zapfding/ fonts/cid/fontforge/ \
	fonts/cmap/adobemapping/ fonts/cmap/dvipdfmx/ fonts/enc/dvips/afm2pl/ \
	fonts/enc/dvips/base/ fonts/enc/dvips/c90/ fonts/enc/dvips/cm-super/ \
	fonts/enc/dvips/context/ fonts/enc/dvips/cs/ \
	fonts/enc/dvips/fontools/ fonts/enc/dvips/jmn/ \
	fonts/enc/dvips/lithuanian/ fonts/enc/dvips/lm/ \
	fonts/enc/dvips/metapost/ fonts/enc/dvips/pl/ fonts/enc/dvips/tetex/ \
	fonts/enc/dvips/tex-gyre/ fonts/enc/dvips/txfonts/ fonts/lig/afm2pl/ \
	fonts/map/dvipdfm/ fonts/map/dvipdfm/lm/ fonts/map/dvipdfmx/ \
	fonts/map/dvipdfmx/updmap/ fonts/map/fontname/ fonts/map/glyphlist/ \
	fonts/map/luatex/ fonts/map/luatex/context/ \
	fonts/misc/cjk-gs-integrate/ fonts/opentype/public/frederika2016 \
	fonts/opentype/public/lm-math/ fonts/opentype/public/lm/ \
	fonts/opentype/public/philokalia fonts/opentype/public/tex-gyre-math/ \
	fonts/opentype/public/tex-gyre/ fonts/pk/ljfour/public/cm/dpi600/ \
	fonts/sfd/dnp/ fonts/source/jknappen/ec \
	fonts/source/public/amsfonts/cmextra/ \
	fonts/source/public/amsfonts/cyrillic/ \
	fonts/source/public/amsfonts/dummy/ \
	fonts/source/public/amsfonts/symbols/ fonts/source/public/armenian/ \
	fonts/source/public/cc-pl/ fonts/source/public/cm/ \
	fonts/source/public/cmextra/ fonts/source/public/cs/ \
	fonts/source/public/etex/ fonts/source/public/euro-ce/ \
	fonts/source/public/eurosym/ fonts/source/public/knuth-lib/ \
	fonts/source/public/knuth-local/ fonts/source/public/latex-fonts/ \
	fonts/source/public/mflogo/ fonts/source/public/pl/ \
	fonts/source/public/rsfs/ fonts/source/public/shade/ \
	fonts/source/public/tipa/ fonts/source/public/wasy/ \
	fonts/tfm/adobe/avantgar/ fonts/tfm/adobe/bookman/ \
	fonts/tfm/adobe/courier/ fonts/tfm/adobe/helvetic/ \
	fonts/tfm/adobe/ncntrsbk/ fonts/tfm/adobe/palatino/ \
	fonts/tfm/adobe/symbol/ fonts/tfm/adobe/times/ \
	fonts/tfm/adobe/utopia/ fonts/tfm/adobe/zapfchan/ \
	fonts/tfm/adobe/zapfding/ fonts/tfm/bitstrea/ \
	fonts/tfm/bitstrea/charter/ fonts/tfm/cs/ fonts/tfm/cs/cs-a35/ \
	fonts/tfm/cs/cs-charter/ fonts/tfm/hoekwater/ fonts/tfm/jknappen/ec \
	fonts/tfm/jmn/ fonts/tfm/metapost/ fonts/tfm/monotype/helvetic/ \
	fonts/tfm/monotype/symbol/ fonts/tfm/public/ae/ \
	fonts/tfm/public/amsfonts/ fonts/tfm/public/amsfonts/cmextra/ \
	fonts/tfm/public/amsfonts/cyrillic/ fonts/tfm/public/amsfonts/dummy/ \
	fonts/tfm/public/amsfonts/euler/ fonts/tfm/public/amsfonts/symbols/ \
	fonts/tfm/public/armenian/ fonts/tfm/public/cc-pl/ \
	fonts/tfm/public/cmextra/ fonts/tfm/public/etex/ \
	fonts/tfm/public/euro-ce/ fonts/tfm/public/eurosym/ \
	fonts/tfm/public/garuda-c90/ fonts/tfm/public/knuth-local/ \
	fonts/tfm/public/lithuanian/ fonts/tfm/public/lm/ \
	fonts/tfm/public/mathpazo/ fonts/tfm/public/mflogo/ \
	fonts/tfm/public/norasi-c90/ fonts/tfm/public/pdftex/ \
	fonts/tfm/public/pslatex/ fonts/tfm/public/pxfonts/ \
	fonts/tfm/public/qpxqtx/ fonts/tfm/public/rsfs/ \
	fonts/tfm/public/tabvar/ fonts/tfm/public/tex-gyre/ \
	fonts/tfm/public/tipa/ fonts/tfm/public/txfonts/ \
	fonts/tfm/public/wasy/ fonts/tfm/urw35vf/ fonts/tfm/urw35vf/avantgar/ \
	fonts/tfm/urw35vf/bookman/ fonts/tfm/urw35vf/courier/ \
	fonts/tfm/urw35vf/helvetic/ fonts/tfm/urw35vf/ncntrsbk/ \
	fonts/tfm/urw35vf/palatino/ fonts/tfm/urw35vf/symbol/ \
	fonts/tfm/urw35vf/times/ fonts/tfm/urw35vf/zapfchan/ \
	fonts/tfm/urw35vf/zapfding/ fonts/type1/adobe/courier/ \
	fonts/type1/adobe/utopia/ fonts/type1/bitstrea/charter/ \
	fonts/type1/hoekwater/context/ fonts/type1/hoekwater/manfnt-font/ \
	fonts/type1/hoekwater/mflogo-font/ fonts/type1/jmn/hans/ \
	fonts/type1/metapost/ fonts/type1/public/amsfonts/cm/ \
	fonts/type1/public/amsfonts/cmextra/ \
	fonts/type1/public/amsfonts/cyrillic/ \
	fonts/type1/public/amsfonts/euler/ \
	fonts/type1/public/amsfonts/latxfont/ \
	fonts/type1/public/amsfonts/symbols/ fonts/type1/public/armenian/ \
	fonts/type1/public/cc-pl/ fonts/type1/public/cm-super/ \
	fonts/type1/public/cs/ fonts/type1/public/eurosym/ \
	fonts/type1/public/fpl/ fonts/type1/public/lm/ \
	fonts/type1/public/mathpazo/ fonts/type1/public/pdftex/ \
	fonts/type1/public/pl/ fonts/type1/public/pxfonts/ \
	fonts/type1/public/rsfs/ fonts/type1/public/tabvar/ \
	fonts/type1/public/tex-gyre/ fonts/type1/public/tipa/ \
	fonts/type1/public/txfonts/ fonts/type1/public/wasy2-ps/ \
	fonts/type1/urw/avantgar/ fonts/type1/urw/bookman/ \
	fonts/type1/urw/courier/ fonts/type1/urw/helvetic/ \
	fonts/type1/urw/ncntrsbk/ fonts/type1/urw/palatino/ \
	fonts/type1/urw/symbol/ fonts/type1/urw/times/ \
	fonts/type1/urw/zapfchan/ fonts/type1/urw/zapfding/ \
	fonts/vf/adobe/avantgar/ fonts/vf/adobe/bookman/ \
	fonts/vf/adobe/courier/ fonts/vf/adobe/helvetic/ \
	fonts/vf/adobe/ncntrsbk/ fonts/vf/adobe/palatino/ \
	fonts/vf/adobe/times/ fonts/vf/adobe/utopia/ fonts/vf/adobe/zapfchan/ \
	fonts/vf/bitstrea/charter/ fonts/vf/cs/ fonts/vf/cs/cs-a35/ \
	fonts/vf/cs/cs-charter/ fonts/vf/monotype/ \
	fonts/vf/monotype/helvetic/ fonts/vf/public/ae/ \
	fonts/vf/public/mathpazo/ fonts/vf/public/pslatex/ \
	fonts/vf/public/pxfonts/ fonts/vf/public/qpxqtx/ \
	fonts/vf/public/txfonts/ fonts/vf/urw35vf/avantgar/ \
	fonts/vf/urw35vf/bookman/ fonts/vf/urw35vf/courier/ \
	fonts/vf/urw35vf/helvetic/ fonts/vf/urw35vf/ncntrsbk/ \
	fonts/vf/urw35vf/palatino/ fonts/vf/urw35vf/times/ \
	fonts/vf/urw35vf/zapfchan/ hbf2gf/ makeindex/babel/ makeindex/base/ \
	makeindex/cnbwp/ makeindex/e-french/ makeindex/fixlatvian/ \
	makeindex/index/ makeindex/latex/ makeindex/memoir/ makeindex/plain/ \
	metafont/feynmf/ metafont/mflua/ metafont/mfpic/ metafont/roex/ \
	metapost/automata/ metapost/base/ metapost/bbcard/ \
	metapost/blockdraw_mp/ metapost/bpolynomial/ metapost/cmarrows/ \
	metapost/config/ metapost/context/ metapost/context/base/ \
	metapost/context/base/common/ metapost/context/base/mpii/ \
	metapost/context/base/mpiv/ metapost/context/fonts/ \
	metapost/context/fonts/mpiv/ metapost/context/third/ \
	metapost/context/third/gnuplot/ metapost/drv/ metapost/dviincl/ \
	metapost/epsincl/ metapost/expressg/ metapost/exteps/ \
	metapost/featpost/ metapost/feynmf/ metapost/garrigues/ \
	metapost/hatching/ metapost/latexmp/ metapost/mcf2graph/ \
	metapost/metago/ metapost/metaobj/ metapost/metaplot/ \
	metapost/metauml/ metapost/mf2pt1/ metapost/mfpic/ metapost/misc/ \
	metapost/mp3d/ metapost/mparrows/ metapost/mpattern/ \
	metapost/mpcolornames/ metapost/mptrees/ metapost/piechartmp/ \
	metapost/repere/ metapost/shapes/ metapost/splines/ metapost/suanpan/ \
	metapost/support/ metapost/support/charlib/ metapost/tabvar/ \
	metapost/textpath/ metapost/threeddice/ mft/ mft/base/ \
	mft/knuth-local/ psutils/ scripts/chktex/ scripts/context/lua/ \
	scripts/context/lua/third/ scripts/context/lua/third/enigma/ \
	scripts/context/lua/third/enigma/mtx-t-enigma.lua/ \
	scripts/context/lua/third/rst/ \
	scripts/context/lua/third/simpleslides/ scripts/context/ruby/ \
	scripts/context/ruby/base/ scripts/context/ruby/base/kpse/ \
	scripts/context/ruby/graphics/ scripts/context/ruby/rslb/ \
	scripts/context/stubs/install/ scripts/context/stubs/setup/ \
	scripts/context/stubs/source/ scripts/context/stubs/win64/ \
	scripts/ketcindy/ scripts/ketcindy/data/ scripts/ketcindy/data/fontF/ \
	scripts/ketcindy/data/polyhedrons_obj/ scripts/ketcindy/ketjava/ \
	scripts/ketcindy/ketlib/ scripts/ketcindy/ketlib/ketpicR/ \
	scripts/ketcindy/ketlib/maximaL/ scripts/ketcindy/ketlib/oshima/ \
	scripts/ketcindy/ketlibC/ scripts/latexindent/LatexIndent/ \
	scripts/lua-alt-getopt/ scripts/luaindex/ scripts/make4ht/ \
	scripts/mflua/ scripts/oberdiek scripts/placeat/ scripts/spelling/ \
	scripts/texlive/lua/ scripts/texlive/var/ tex/context/base/mkiv/ \
	tex/context/bib/ tex/context/colors/ tex/context/fonts/ \
	tex/context/interface/ tex/context/modules/common/ \
	tex/context/modules/mkii/ tex/context/modules/mkiv/ \
	tex/context/patterns/common/ tex/context/patterns/mkii/ \
	tex/context/patterns/mkiv/ tex/context/sample/common/ \
	tex/context/test/mkiv/ tex/context/third/account/ \
	tex/context/third/algorithmic/ tex/context/third/animation/ \
	tex/context/third/annotation/ tex/context/third/asymptote/ \
	tex/context/third/bnf/ tex/context/third/chromato/ \
	tex/context/third/cmscbf/ tex/context/third/cmttbf/ \
	tex/context/third/construction-plan/ \
	tex/context/third/cyrillicnumbers/ tex/context/third/degrade/ \
	tex/context/third/enigma/ tex/context/third/enigma/t-enigma.mkv/ \
	tex/context/third/fancybreak/ tex/context/third/filter/ \
	tex/context/third/french/ tex/context/third/fullpage/ \
	tex/context/third/gantt/ tex/context/third/gnuplot/ \
	tex/context/third/handlecsv/ tex/context/third/inifile/ \
	tex/context/third/layout/ tex/context/third/letter/ \
	tex/context/third/letter/base/ tex/context/third/letter/style/ \
	tex/context/third/lettrine/ tex/context/third/mathsets/ \
	tex/context/third/pgf/ tex/context/third/rst/ tex/context/third/ruby/ \
	tex/context/third/simplefonts/ tex/context/third/simpleslides/ \
	tex/context/third/title/ tex/context/third/transliterator/ \
	tex/context/third/typearea/ tex/context/third/typescripts/ \
	tex/context/third/vim/ tex/context/third/visualcounter/ \
	tex/context/user/ tex/context/user/mkii/ tex/cslatex/cspsfonts/ \
	tex/csplain/fonts/ tex/csplain/opmac/ tex/fontinst/afm2pl/ \
	tex/fontinst/base/ tex/fontinst/latinetx/ tex/fontinst/latinmtx/ \
	tex/fontinst/mathetx/ tex/fontinst/mathmtx/ tex/fontinst/misc/ \
	tex/fontinst/smbletx/ tex/fontinst/smblmtx/ tex/lualatex/combofont/ \
	tex/lualatex/cstypo/ tex/lualatex/lua-check-hyphen/ \
	tex/lualatex/luabibentry/ tex/lualatex/luacode/ \
	tex/lualatex/luahyphenrules/ tex/lualatex/luaindex/ \
	tex/lualatex/luainputenc/ tex/lualatex/lualatex-math/ \
	tex/lualatex/luamesh/ tex/lualatex/luasseq/ tex/lualatex/luatextra/ \
	tex/lualatex/luatodonotes/ tex/lualatex/novel/ \
	tex/lualatex/pgfmolbio/ tex/lualatex/placeat/ tex/lualatex/plantuml/ \
	tex/lualatex/selnolig/ tex/lualatex/showhyphens/ \
	tex/lualatex/typewriter/ tex/lualatex/wallcalendar/ \
	tex/luatex/chickenize/ tex/luatex/ctablestack/ tex/luatex/cstypo/ \
	tex/luatex/hyph-utf8/ tex/luatex/interpreter/ \
	tex/luatex/lua-visual-debug/ tex/luatex/lualibs/ tex/luatex/luamplib/ \
	tex/luatex/luaotfload/ tex/luatex/luapackageloader/ \
	tex/luatex/luatexbase/ tex/luatex/luatexko/ tex/luatex/luaxml/ \
	tex/luatex/nodetree/ tex/luatex/spelling/ tex/plain/amsfonts/ \
	tex/plain/armenian/ tex/plain/cweb/ tex/plain/encxvlna/ \
	tex/plain/enigma/ tex/plain/epsf-dvipdfmx/ tex/plain/figflow/ \
	tex/plain/fixpdfmag/ tex/plain/font-change/ tex/plain/fontch/ \
	tex/plain/fp/ tex/plain/getoptk/ tex/plain/gfnotation/ \
	tex/plain/graphics-pln/ tex/plain/gustlib/ \
	tex/plain/gustlib/biblotex/ tex/plain/gustlib/licz/ \
	tex/plain/gustlib/map/ tex/plain/gustlib/plbtx993/ \
	tex/plain/gustlib/plmac218/ tex/plain/hyplain/ tex/plain/ifetex/ \
	tex/plain/js-misc/ tex/plain/knuth-lib/ tex/plain/knuth-local/ \
	tex/plain/makeindex/ tex/plain/metatex/ tex/plain/mkpattern/ \
	tex/plain/newsletr/ tex/plain/pgf/ tex/plain/pitex/ \
	tex/plain/placeins-plain/ tex/plain/plnfss/ tex/plain/plstmary/ \
	tex/plain/rsfs/ tex/plain/timetable/ tex/plain/treetex/ \
	tex/plain/varisize/ tex/plain/wasy/ tex/support/ \
	tex/support/adhocfilelist/ tex/texinfo/ tex/xetex/font-change-xetex/ \
	tex/xetex/xesearch/ tex/xetex/xetex-pstricks/ \
	tex/xetex/xetexfontinfo/ tex/xetex/xetexko/ tex4ht/base/unix/ \
	tex4ht/base/win32/ tex4ht/bin/ tex4ht/ht-fonts/ tex4ht/xtpipes/ \
	texdoc/ texdoctk/

TEXMF_DIRS_GENERIC=	\
	abbr abstyles apnum autoaligne babel-albanian babel-basque \
	babel-bosnian babel-breton babel-catalan babel-croatian babel-czech \
	babel-danish babel-dutch babel-english babel-estonian babel-finnish \
	babel-french babel-friulan babel-galician babel-german \
	babel-hungarian babel-icelandic babel-irish babel-italian \
	babel-kurmanji babel-latin babel-latvian babel-macedonian babel-norsk \
	babel-occitan babel-piedmontese babel-polish babel-portuges \
	babel-romanian babel-romansh babel-samin babel-scottish babel-slovak \
	babel-slovenian babel-spanglish babel-spanish babel-swedish \
	babel-turkish babel-welsh barr bibtex borceux c-pascal chronosys \
	dirtree docbytex dvips e-french eijkhout enigma epigram epsf fltpoint \
	fntproof genmisc german hyphenex iftex ifxetex insbox kastrup \
	knuth-lib langcode librarian listofitems mathdots metapost mfpic \
	navigator oberdiek ofs olsak-misc path pdf-trans pdftex pgf qpxqtx \
	randomlist schemata shade simplekv systeme tabto-generic termmenu \
	tex-ps tex4ht thumbpdf tracklang trigonometry ulem upca variations \
	xecyr xkeyval xlop yax

TEXMF_DIRS_LATEX=	\
	accfonts ae aeguill amscls amsfonts amsmath anysize armenian \
	asymptote auto-pst-pdf-lua avantgar babelbib basque-book basque-date \
	biblatex bibleref-french bibleref-german bookman bredzenie breqn \
	bundledoc caption carlisle checklistings cite cjk cjkpunct cm-super \
	cmap cnbwp cntformats codicefiscaleitaliano context courier crop \
	csbulletin dhua droit-fr emp encxvlna enigma enumitem eso-pic \
	etex-pkg etoolbox euenc euler euro eurosym extsizes fancyhdr fancyref \
	fancyvrb feupphdteses feynmf feynmp-auto filecontents fixltxhyph \
	float fontinst fontspec fp frletter frontespizio geometry germbib \
	germkorr gloss-occitan gmp graphics-cfg graphics-def hausarbeit-jura \
	helvetic hrlatex hyperref ifetex impnattypo index itnumpar jknapltx \
	ketcindy koma-script l3experimental l3kernel l3packages latex2man \
	latexbug latexfileinfo-pkgs layaureo lineno listings listings-ext \
	lithuanian lm ltxmisc lwarp macros2e mathtools memoir metalogo mflogo \
	mfnfss mfpic4ode microtype milog mpgraphics ms mwcls natbib ncntrsbk \
	nevelok ntgclass numprint oberdiek ordinalpt palatino parskip pfarrei \
	pgf/basiclayer pgf/compatibility pgf/frontendlayer pgf/math \
	pgf/systemlayer pgf/utilities pgfopts polski polyglossia \
	przechlewski-book psfrag pslatex psnfss pspicture pxfonts pxtatescale \
	pythontex r_und_s realscripts sansmath section sepnum setspace \
	spanish-mx subfig symbol tabvar tdsfrmath termcal-de tex-gyre \
	tex4ebook texosquery textpath times tipa titlesec tracklang \
	translator turkmen txfonts typehtml ucharcat ucs udesoftec uhrzeit \
	umlaute underscore unicode-math url wasysym xcjk2uni xcolor \
	xebaposter xkeyval zapfchan zapfding zxjafont

TEXMF_DOCDIRS+=	bibtex/abstyles generic/apnum generic/pgf/pgfmanual.pdf \
	generic/autoaligne generic/barr generic/randomlist/randomlist.pdf \
	metapost/automata metapost/bbcard
TEXMF_DOCDIRS_LATEX:=	${TEXMF_DIRS_LATEX:Npgf*}

.for exc in \
	accfonts ae amsfonts armenian asymptote\
	avantgar babelbib bookman bundledoc cm-super\
	context courier ctable encxvlna enigma eurosym fontinst\
	germbib helvetic ketcindy latex2man latexconfig lm\
	ltxmisc multido ncntrsbk palatino compatibility\
	pslatex pxfonts seminar symbol tex-gyre tex4ebook texosquery\
	textpath times tipa tracklang txfonts zapfchan zapfding
TEXMF_DOCDIRS_LATEX:=${TEXMF_DOCDIRS_LATEX:N${exc}}
.endfor

TEXMF_SHEBANG_FILES_DOCS=	\
	share/doc/texlive-texmf/ucs/latexout.pl\
	share/doc/texlive-texmf/ucs/unsupported/u2ps\
	share/doc/texlive-texmf/ucs/discovermacro.pl\
	share/doc/texlive-texmf/ucs/makeunidef.pl

post-install-texmf:
	# texlive-bin contains make4ht script
	${RM} ${STAGEDIR}${TEXMFDISTDIR}/scripts/make4ht/make4ht
	${RM} ${STAGEDIR}${TEXMFDISTDIR}/scripts/oberdiek/pdfatfi.pl

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
