# $FreeBSD$

COMMENT=	Various (not usual) document types
TEXMF_CATEG=	doctypes

TEXMF_DIRS_LATEX=	\
	a0poster bookcover booklet cheatsheet contracard cooking \
	cooking-units cuisine dvdcoll elegantbook elegantnote elegantpaper \
	elzcards factura facsimile flacards flashcards g-brief gcard \
	image-gallery invoice invoice-class invoice2 isodoc leaflet lettre \
	magaz mceinleger modeles-factures-belges-assocs modernposter modroman \
	newlfm newspaper octavo papercdcase papertex petiteannonce postcards \
	pressrelease recipe recipebook recipecard sciposter scrlttr2copy \
	sffms simplecd simpleinvoice stubs ticket xcookybooky yaletter \
	schedule sdaps akktex akletter bankstatement block bookest cd cd-cover \
	cdpbundl

.include "${.CURDIR}/../texlive-texmf-all/bsd.texmf.mk"
