# $FreeBSD$

COMMENT=	Various (not usual) document types
TEXMF_CATEG=	doctypes

TEXMF_DIRS_LATEX=	\
	a0poster bookcover booklet cheatsheet dvdcoll elzcards facsimile factura \
	flacards flashcards g-brief gcard image-gallery invoice-class invoice \
	invoice2 isodoc leaflet lettre\
	sciposter 
TEXMF_DOCDIRS_LATEX=	${TEXMF_DIRS_LATEX}

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
