# $FreeBSD$

COMMENT=	Various (not usual) document types
TEXMF_CATEG=	doctypes

TEXMF_DIRS_LATEX=	\
	a0poster bookcover booklet cheatsheet dvdcoll elzcards facsimile factura \
	flacards flashcards g-brief gcard image-gallery invoice-class invoice \
	invoice2 isodoc leaflet lettre magaz mceinleger\
	cooking-units cooking \
	modeles-factures-belges-assocs \
		contracard \
		cuisine \
	xcookybooky \
	elegantpaper \
	elegantnote \
	elegantbook \
		scrlttr2copy\
		sffms\
		modernposter\
		modroman\
		newlfm\
		newspaper\
		papertex\
		octavo\
		papercdcase\
		petiteannonce\
		postcards\
		pressrelease\
		recipe\
		recipebook\
		simplecd\
		simpleinvoice\
		stubs\
		ticket\
		recipecard\
		yaletter\
	sciposter 
TEXMF_DOCDIRS_LATEX=	${TEXMF_DIRS_LATEX}

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
