# $FreeBSD$

COMMENT=	Packages to plot data
TEXMF_CATEG=	plot
TEXMF_DIRS=	\
	scripts/pgfplots tex/generic/pst-plot
TEXMF_DIRS_LATEX=	\
	bodegraph histogr makeplot mgltex numericplots pgfplots \
	pst-2dplot pst-3dplot pst-func pst-infixplot pst-plot tikz-3dplot
TEXMF_DOCDIRS_GENERIC=	pst-2dplot pst-3dplot \
		pst-func pst-infixplot pst-plot
TEXMF_DOCDIRS_LATEX_EXCLUDE=	${TEXMF_DOCDIRS_GENERIC}

.include "${.CURDIR}/../texlive-texmf-all/bsd.texmf.mk"
