# $FreeBSD$

COMMENT=	Change geometry of page layout and change text layouts
TEXMF_CATEG=	geometry

TEXMF_DIRS_LATEX=	\
	a4wide a5comb addlines adjmulticol bizcard blowup bxpapersize \
	canoniclayout centeredline changelayout changepage fjodor fullwidth layouts \
	midpage rmpage scale semioneside stdpage subfigmat subfigure subfloat \
	twoinone vmargin zwpagelayout

.include "${.CURDIR}/../texlive-texmf-all/bsd.texmf.mk"
