# $FreeBSD$

COMMENT=	To change geometry of page layout
TEXMF_CATEG=	geometry

TEXMF_DIRS_LATEX=	\
	a4wide a5comb addlines adjmulticol bizcard blowup bxpapersize \
	canoniclayout changelayout changepage fjodor fullwidth layouts \
	midpage rmpage scale semioneside stdpage subfigmat subfigure subfloat \
	twoinone vmargin zwpagelayout
TEXMF_DOCDIRS_LATEX=	${TEXMF_DIRS_LATEX}

MASTERDIR=	${.CURDIR}/../texlive-texmf-all

.include "${MASTERDIR}/Makefile"
